### ISSUE TITLE
HISE license edit

### ISSUE THREAD

**Issue by davidhealey** [christophhart/HISE#105]
I just noticed this in the HISE license file

>  HISE is based on the JUCE library, 
>  which must be separately licensed for commercial applications:

I think it would be more appropriate to say proprietary or closed source, than commercial. There is nothing stopping a GPL product being commercial.

**Comment by christophhart** [comment]
I'll update the copyright header with a funky ASCII art, fix a few spelling mistakes and incorporate this change with the next big update - changing all files is a bit annoying for the commit history.

**Comment by frink** [comment]
Can this one be closed?
