### ISSUE TITLE
Mojave:  Projucer can't be opened

### ISSUE THREAD

**Issue by aumhaa** [christophhart/HISE#113]
I'm trying to compile HISE by following readme instructions, however Projucer for MacOS will not open.  I've checked on 3 different machines, all running 10.14.3 and all of them behave the same.  I'm only seeing a few Finder errors in Console, nothing that very helpful:

error	10:55:26.989788 -0800	Finder	Unable to load Info.plist exceptions (eGPUOverrides)
error	10:55:27.006907 -0800	Finder	spawn_via_launchd() failed, errno=111 label=<private> path=<private> flags=1
default	10:55:27.007126 -0800	Finder	spawn_via_launchd() failed, errno=111 label=com.juce.theprojucer.54224 path=/Users/amounra/GitHub/HISE/tools/projucer/Projucer.app/Contents/MacOS/Projucer flags=1

![screen shot 2019-03-01 at 10 50 19 am](https://user-images.githubusercontent.com/4337906/53659631-e9226700-3c10-11e9-96f6-8d98281e5f3b.png)

Any advice is welcome and appreciated :)

**Comment by christophhart** [comment]
You can compile the Projucer yourself if the supplied binary isn‘t working. The xcode project is located at JUCE/extras/projucer

**Comment by aumhaa** [comment]
Thanks, that seems to be working.
