### ISSUE TITLE
Global LFO doesn't start again after switching it OFF and restarting HISE 

### ISSUE THREAD

**Issue by ustk** [christophhart/HISE#140]
Once switched OFF and preset saved, a global LFO won't start again at the next opening of Hise.
Also, Hise crashes if you try to turn ON the target the global modulator is connected to.

Topic + Snippet:
https://forum.hise.audio/topic/1558/global-lfos-don-t-want-to-start-and-crash-hise/2

**Comment by christophhart** [comment]
fixed with commit e4a0e4d810ef2284ed825005d5e266150b14a29e
