### ISSUE TITLE
Problem building on Ubuntu/Pop OS 19.04

### ISSUE THREAD

**Issue by hojo9595** [christophhart/HISE#141]
Having issues building the standalone app on Ubuntu.

`At global scope:
cc1plus: warning: unrecognized command line option ‘-Wno-inconsistent-missing-override’
make: *** [Makefile:154: build/intermediate/Debug/MainComponent_a6ffb4a5.o] Error 1
`

**Comment by swestlake** [comment]
I was having a similar issue, do you get the "sqrtf" error on output as well? basically if you edit  hi_scripting/scripting/scripting_audio_processor/ScriptDspModules.h  and on line 502 rename the function from sqrtf to sqrt , it will compile.. as to app functionality I am currently seeing how well things work..
