### ISSUE TITLE
No sound when using MIDI keyboard

### ISSUE THREAD

**Issue by arminhupka** [christophhart/HISE#142]
HISE not make any sounds when i click keys on MIDI keyboard. 
MIDI Signal icon blinking when i press key and i see which key i pressed on virtual keyboard.
When i click keys on virtual keyboard everything works fine.
I tried build VSTi but not work aswell.

**Comment by davidhealey** [comment]
I think this has been solved now. You have to build the script node branch. This bug only affected MacOS as far as I'm aware.
