### ISSUE TITLE
can be used on ubuntu with Ardour?

### ISSUE THREAD

**Issue by zkbqhuang** [christophhart/HISE#152]
can be used on ubuntu with Ardour?

**Comment by davidhealey** [comment]
Yes. But you'll probably use the standalone version rather than the plugin version most of the time while developing your plugins. At least I do, I only tend to use the plugin version for testing specific things.

**Comment by zkbqhuang** [comment]
> Yes. But you'll probably use the standalone version rather than the plugin version most of the time while developing your plugins. At least I do, I only tend to use the plugin version for testing specific things.

thank you :)

**Comment by zkbqhuang** [comment]
> Yes. But you'll probably use the standalone version rather than the plugin version most of the time while developing your plugins. At least I do, I only tend to use the plugin version for testing specific things.

thank you :)
