### ISSUE TITLE
Can't build latest scriptnode 

### ISSUE THREAD

**Issue by arminhupka** [christophhart/HISE#157]
I can't build this build df2f48a

snex_jit_UnitTest.cpp
![obraz](https://user-images.githubusercontent.com/49194860/79920801-3ffc8880-8431-11ea-895c-b3f997548df3.png)

**Comment by davidhealey** [comment]
This is a development branch so expect it to be unable to build on some commits. You can go back through the commit history until you find one that builds successfully. Last one I built from was in January but I think some later ones will build also.
