### ISSUE TITLE
How to make drum kit with OH, Room and other mics, please tutorial needed

### ISSUE THREAD

**Issue by fewtubefx** [christophhart/HISE#161]
How to make drum kit with OH, Room and other mics, please tutorial needed. Please.

**Comment by Linuxvst** [comment]
Check This Tutorial!
https://www.youtube.com/watch?v=sV9aMTphmDE&list=PLynv7CujPCfbH2OPE-cC5F4ZK-sVGkBwx&index=52&t=20s

**Comment by davidhealey** [comment]
You'll probably have more luck with this sort of question by asking it on the forum. https://forum.hise.audio/
