### ISSUE TITLE
The Preset Folder was not found

### ISSUE THREAD

**Issue by tekord** [christophhart/HISE#17]
I just installed HISE on Windows x64 and everytime I click on the File menu I got this annoying message:

![hise_2017-03-11_00-45-23](https://cloud.githubusercontent.com/assets/1286100/23814346/44c61f0c-05f4-11e7-8a8f-745a74d7a122.png)

What is the documentation folder? What should I do to fix it?

**Comment by christophhart** [comment]
Yeah, this thing is long gone (I fixed this about two months ago), but didn't upload a new build since then.
