### ISSUE TITLE
Errors building on MacOS 11.2.1

### ISSUE THREAD

**Issue by ajw0100** [christophhart/HISE#173]
This could very well be something I misconfigured. Please let me know if I can provide more info.
```
$ sw_vers
ProductName:    macOS
ProductVersion: 11.2.1
BuildVersion:   20D74
```
I built off 9813dfdcfceff2bdd605996b90c51e51b71105d1. Here is the build log:
https://gist.github.com/ajw0100/5008f3c742e017292a77e8f19ee745e2

**Comment by davidhealey** [comment]
What version of Xcode are you using?

**Comment by ajw0100** [comment]
@davidhealey Version 12.4 (12D4e)

**Comment by davidhealey** [comment]
You need to use 10.3

**Comment by ajw0100** [comment]
@davidhealey Thanks, that worked. I submitted a PR to update the docs: https://github.com/christophhart/hise_documentation/pull/7.
