### ISSUE TITLE
Simple Copy Protection bug on Linux  - - Engine.dumpAsJSON(data, "../RegistrationInfo.js");

### ISSUE THREAD

**Issue by Linuxvst** [christophhart/HISE#181]
this bug is Happening with the latest Scriptnode, & Release version 2.1.0  and i guess all the Previous Versions 

Engine.dumpAsJSON(data, "../RegistrationInfo.js");
is not Creating the "RegistrationInfo.js" File 
under  Home/.config/Company/Plugin Name/

this Problem is only Happening on "Linux" (Mac & Windows are OK!)

On Linux:
When using Hise app everything is ok 
if i enter a valid serial number in the Serial Number Box 
the file "RegistrationInfo.js" is automatically created under the plugin project folder
and simple Copy Protection Works!

but after exporting the Stand Alone or the Vst plugin

  
The Problem is:
when i enter a valid serial number in the Serial Box and click submit
it is not creating "RegistrationInfo.js" under Home/.config/Company/Plugin Name/
i searched everywhere on the drive it is simply not created anywhere! 
Simple Copy Protection is not working: (i tested on Ubuntu Studio, Linux Mint, Fedora, mx Linux)

i Checked to see if Files were Created under Home/.config/Company/Plugin name

Expansions Folder, User Presets Folder, DeviceSettings.xml, GeneralSettings.xml, LinkLinux
all were created under Home/.config/Company/Plugin name  
"as it should"
but it is missing the RegistratioInfo.js file

if i copy RegistrationInfo.js manually 
to the Home/.config/Company/Plugin name/
and i Start the Standalone or VST Plugin 
then the Simple copy protection works

just in case you did not know about this Bug
Hope it Helps!

**Comment by davidhealey** [comment]
> Engine.dumpAsJSON(data,` "../RegistrationInfo.js");

Is that backtick (after data,) meant to be there or is it a typo?

**Comment by Linuxvst** [comment]
it is meant to be there 
[https://forum.hise.audio/topic/1204/simple-copy-protection-done-right/19](url)

 and it works under Windows and Mac 
 there is something wrong with Linux
