### ISSUE TITLE
Can't export with Visual Studio 2019

### ISSUE THREAD

**Issue by Ceebox** [christophhart/HISE#183]
Hi there, I am using the latest release version of HISE with VS2019, and I cannot build my plugin.

I am running rather low on space so I can't install VS2017 along with 2019 in order to export. Is there anything I can do?

**Comment by davidhealey** [comment]
The current version won't work with 2019, you'll need to use 2017.

**Comment by davidhealey** [comment]
If you use the latest develop branch you can use VS 2019, you'll need to do some manual edits to the .bat file so it can find the right executable and if that doesn't work you'll need to open the VS solution manually and retarget it for VS2019.
