### ISSUE TITLE
AU Write Automation not working

### ISSUE THREAD

**Issue by dustbro** [christophhart/HISE#254]
Forum discussion
https://forum.hise.audio/topic/5068/au-write-automation-still-broken

Commit
https://github.com/christophhart/HISE/commit/ecd5f153a7d47e335caf52f446b63cb7929598c7

Conditions to reproduce the bug
OS: macOS
HISE: N/A
Compiled Project: yes

Problem Description
AU parameter Write Automation is not working from plug-in GUI in Logic. Automation manually created in Automation Lanes works as expected. 

Possible relevant discussion:
https://forum.juce.com/t/au-parameter-automation-issue-togglebutton-does-not-write/34277/39

Snippet
HiseSnippet 796.3ocsUssSaCCF1tTyV6XSiId.xkfDC0NXGj1Ez0SnJFkpE.scExMwgZUG6nDGFEzj1E64YuBiWk8Fr2fsemDZCitBTokKp5+I6u+Ce+tWnxgEEoBQ3RGLJfgvKQrGI0CZLfxknNMQ3mP1iFoYgVoppOJfFEwbQX7B6XTfKUDk78qsqSEToCahJD5HE2g8dtOWOQauZ6xEh1TW1Ab+bduUsNNJYCkPEC3YARET.0YH8DVWpwsBDDdwVtbsJzVS0rHvm5J2Q1CTeVl5+Q7HdeAyHTEYCGTpZTiAbgauqx0HDBWr2jLegzLeExdbW9X8Sp.OMwf0jHxWCvElEjpdOfDNGjJlBokI1Ng7.8DKF77HRGIzP7nPoNOTR8EgujzPANH0a3SGxZGBBiCX0MqTYcK3m0dqWrzQyURKkrqRy1Wt5Zkunboxeor0eaxyap1LWSnRHXgS0ro6FNq.WUF62mEtt0oTQLariP5e8Z5h2sZpSZVmyQkrijq2OfkI2VIbM0Jy+uYG.kU1fdQgLDBtpS5DOIqSXK3trPDGNjGP1Up5WEk.97y7n+Uv0i0ZkLI3RjTgoE9gcZR0TyDQFf.PFvB0bSs.2jcJPoRmOJQZxhFpUAIH1OPIMvGuzsh4yFege8nZilb6cqEoGYprKl3Hxm65JX8TQbSmKGW+GvJg.a94IH+hU99N+77usse90AHjO8r7aGhh873mkvi83B+HMfsN9.8FgeF4vHlkKyiFKzVQCgyQvkCYtGnR7GkK4JdGpo4t2OkK8treMzMIY.8V4FKn5qy4MK2xLXR87DMCaRBkjQ4Su6whfJybQvcEhKS5w0NClNFKLELZlq+Ofwr0mOlzxyi4nm.vhj1ebd2UdKW+GTwZt7j8nvPDzrIci8sgWMbXvsKkLAb3DbACULUthQ1TArYR2DgeCeYFqZjwYFqdkQX70ITcrSJW1rf9gIZ.LISdOpD7vHHaMlBSHU1nhgxvO1wwj9OuJBM8XdwbDylyQLaMGw7x4HlWMGw754Hl2LyXLOS+tXsxOkN.J50JYUJF2RRgIqjoPze.VTAW4B

**Comment by davidhealey** [comment]
I think this can be closed now?

**Comment by beyhanklc** [comment]
I've tried on the Logic Pro 10.7.3 (Monterey M1 Max), I think it works with that commit now, congrats!
