### ISSUE TITLE
Reference monolith doesn't work when the sample maps have different numbers of round robins

### ISSUE THREAD

**Issue by davidhealey** [christophhart/HISE#255]
### Forum Discussion
https://forum.hise.audio/topic/2921/reverse-sampler-behavior-identical-sample-maps-in-two-samplers-will-both-be-reversed/21?_=1645225647192

### Commit
4c64ee1944780c039c7566bf085f51ecaa45a931

### Conditions to reproduce the bug

OS: GNU/Linux
HISE: yes
Compiled Project: yes

### Problem Description

When two sample maps with differing numbers of round robin groups reference the same .ch monolith the samples are not played back correctly.

The example project contains two samplers, the buttons on the UI can be used to control which sampler is triggered. 

Triggering notes on the first sampler (which has 2 RR groups) is fine. When notes are triggered on the second sampler they don't always play the correct samples. You'll hear this if you play a scale.

[Shared Samples Test.zip](https://github.com/christophhart/HISE/files/8101074/Shared.Samples.Test.zip)

**Comment by christoph-hart** [comment]
Yeah that's a big problem. As soon as you remove samples from a samplemap that references another monolith, you get all kinds of index mismatch issues (in this case it uses the wrong sample offsets, but fixing this manually in the XML leads to the next crash).

I would recommend to just not do that LOL and if you need to reference a monolith keep the sample amount the same and just remap the ones you don't need (in this case I would leave the RR group at two and then just manually enforce the first RR group.

**Comment by davidhealey** [comment]
I think that's a suitable workaround.
