### ISSUE TITLE
Header's are ignored with Server.downloadFile

### ISSUE THREAD

**Issue by davidhealey** [christophhart/HISE#256]
### Forum Discussion
https://forum.hise.audio/topic/4003/setting-server-headers-for-downloads?_=1645228424997

### Commit
https://github.com/christophhart/HISE/commit/4c64ee1944780c039c7566bf085f51ecaa45a931

### Conditions to reproduce the bug
OS: GNU/Linux
HISE: yes
Compiled Project: yes

### Problem Description

HISE doesn't send headers along with requests made using Server.downloadFile(). This isn't a critical issue but it would be useful for validating/authorizing file download requests.

**Comment by christoph-hart** [comment]
Should be fixed now, but please reopen if the issue remains
