### ISSUE TITLE
MIDI Drag to DAW

### ISSUE THREAD

**Issue by mwins2022** [christophhart/HISE#262]
**Forum discussion**
https://forum.hise.audio/topic/4505/drag-and-drop-midi-develop-branch?_=1646091783921

**Commit**
Dec 4 2021 to Latest

**Conditions to reproduce the bug**
OS: both macOS / Windows
HISE: yes
Compiled Project: yes

**Problem Description**
When dragging and dropping MIDI to a DAW, the drag and drop function only works initially. If you need to drag and drop multiple times, the function does not work. 

**Hise Snippet**
`HiseSnippet 1070.3oc0V81aaSDF+babgDnvFvG.qJgTmVwJoszMMdAYItg40kVKb51JJhoq1mStF66LmO2lroIwK6mK9Dw2fwyY6lXixpJQBg3dQTd924eO++bDbORRBWfzpOXVLAo845tyXxwcGioLjsER6q0in9TCeAO1fLEGEGRPclEiSRH9HMs0+IkhZ0qgxN+4O1AGhYdjErPnWxodjWPinxEbcZeDMLrG1mLfFUR68aa6wYc4g7T.Tqq2DEi8lfGQNFqTaMcj1FG5SkbgqDKIIfNc39ybGyuhkq+KoIzyAPBDsPtvEkyF0cLMz24FGNAgzp4rv8WO28+F89f2Nm+hvv8xDXrvhxw.s0pBoZUfTqOFj5wC8UWvGAdqUBdexMYmL3EhmQDYv5Kz6aaYajyoUEP0MUHHLoK42RIUSHsKDMP.g1x4tWv4wGxv.T8KyVc6mCp5FSpJPa8aKUz5tmJPJ2pGMjj422P.Zq7QHmagkXj1D8GcfIavAG83tctv6YllW7bG2Ai5clIb5Y5XZZc49r2Zc5zjd.m.eSS6SBOy1wbJ8ri5LkZZ9ZVP+8dXpoSGymY0wo+nml77fcad3die3Ecu5sGaZ6+KmddGSj56mWxsud2mL7zDhHYXBFP3PKtWZDD9RFNfDEyGNG6CmpNlP+BD+Uk0tzQLrLU.2h9woQcvfuNO7Yz9XdDEjm08Uv7dssHrkwVkZfvrPVtwJOeUIkf9eaval57ebvqTGWs7Nt6q65InwxERTQ0OS2lIIh.rW0gg45hz9C8tbPAlzLBOgzS.DyMX6CZ1bGC3mG7CMZDjx7jTNyfyNlKImv19AMdWi5MdeCi+tnffkJS8gD7vPhXohUQRwsY31rznyIhcLtDGlRlqHD.p1auwcq21K2uKoHmYynxShIEzKl50ZYSBJBbv+N0NqxEhqE7.8hIBIUAGMKxkvVk7jTccKRxDIONSWnrhotAsFxhY54okdgbrjxFMP0cnJy9R8xrZglNuV32CZOaQgwu197Q2rQp9F.iuUwkJIQK3d80W+gpb2qP4L1EdPNb+pro3mbIQ.CVcvLRXIy1UYlkkUlY4stt5uayFFFaMONY6u0SL1p7j+s1ISCalOYJHqYNIDpC4W8JtXRBrEk.BBvgIjMa7dzRJ0gUbb+zPUyS48dpE7EBfBmJk6pZZVBUNqxRg69xvlKcY3RKKtiv895NTo23ki20VBdU6a9WFuEOsXS8CCBHdxEfslduWupui3e.T9YdppFuOVJnSyGl5BEZdD.ILn3C9P5ZqoJRyoapnUQFWByOi3CvoPXKEsVgvV2HDEg8D723kORQsD+Sy3.XhksGntdeEsQKT1XFvN8llMQpmV9FOOUn36.ruba1cErYuUvl8WAa99UvlCVAadzJXyiuUaTifdZpjGk2l.LbNLebi17m.psN5u7Mv7bA`

**Comment by christoph-hart** [comment]
I can drag a MIDI file multiple times on Windows in Ableton and REAPER (haven't checked the compiled plugin but you said it doesn't work for you in HISE neither).

**Comment by musikboden** [comment]
This was fixed by @ustk a time ago
https://forum.hise.audio/topic/4575/midi-player-and-drag-to-daw-almost-there-speed-buttons-success/25?_=1651737638396
