### ISSUE TITLE
keypressCallback bad focus from parent panel

### ISSUE THREAD

**Issue by ustk** [christophhart/HISE#267]
### Forum Discussion
[https://forum.hise.audio/topic/4887/panel-keypresscallback-and-focus/27](https://forum.hise.audio/topic/4887/panel-keypresscallback-and-focus/27)

### Commit
[https://github.com/christophhart/HISE/commit/63f7a240857c8a269a7cc82d93009dda079966f0](https://github.com/christophhart/HISE/commit/63f7a240857c8a269a7cc82d93009dda079966f0)

OS: Only tested on MacOS
HISE: YES
Compiled Project: YES

### Description
When clicking in a parent panel, the first child gets in focus automatically which makes the keypressCB unusable.
Notice that clicking an external panel loses the focus which is a nice thing. This should be the same with the parent.

### Snippet
`HiseSnippet 1525.3ocsW8taaTDDeujbPcfhnR7.rjOclj3Zmz+ojVvINNnnz+XEmV.UUUVe2Zeay5cOc2dI0fhfOySAOJ8AfGBdD3C7cXlcOaeN0o.QzSJN2ty+9syL6Ly0IUGxyxzoDuJGOJgS79X+tiTl3VwLghbvdDuOw+QrLCOk51Z2QIrrLdDwyawuF2vqxRD6ye7U6xjLUHe5VDxyzhP9CECElo61o4gBobeVD+XwvRbeqlGDpUszRcNfmE8qSRXgmvFveLCYaAeh2GzNRXzocMLCOi3szt5nQci0mob7+LQlnmjiKZP5BJxs89ZYDhXbWRqXgLpy3ycFAzRmodgEcdgOy+QhHwj8m5M9TKA5TIJ6O7VXV3s3LvqQY3UuD7lCj7JAokbP5F9cCSEIloTP77Q9GnffSeF31KCEGujE9de+VZfCko1P1I78SgESjH3N0quFE9o51KuL35yLzSYozNLEW1f9.5XIGvMszCSzJXQvJNxq.x3dqVDyvpk.7+7W.5ouNkFHdP8soh6uI7ypqVc4eb4JnhQdJjgEE4N03x.PWUlQYOW7Bf2DX6jZYbSGclvHzpfF.daTmtJ7S8uPr1XsA.7aDQl3fpquAvw8rGnBQgHm4HctQn3A8yUgV8Ln5xU.PUYPs9Pp3NRYP8WuwF6aePv.DxvCMlJBjt8smRBHJ5GXhEYNrFyx1WGlmAZDEKJkc1Q7PiiC.XOTGxj6pyUQYA0qBvuV8B0T1Ft+kU6rXggWf.TU6HECT7ni4u1TxlFX4ZzKyBqDBwoTdDFhpbtyXVewg7QcRgbmVLorGb0Zp+P26UUoNWxMuI8XHSgxnRs9DJyXsCUnf+yoXVhVxA9Z4dqVRJ3fCLoX9DpFK3cNIXYMgy6.2fTC3nOBsQk218Agaj8wKQkbN7GWlwGKT1YBSXrUqmvG0RGY0miFB61casSm1aQ2iK4FtEtnixRNjkwoab2sny5DAqtxJaSsrTghO8R4rS1drJOp8wO8nGSOr82sE8U4v8CoNyo49HJmp5FaVnZjA6I.RpoEJtxEz5t6z5vtc1oEf0i3C0m5znDJyRCiYfmDteNU02aK5ai5Y2nVVduLCDHFDTesKRSxUCLwq2n51yGM6jjvUQTlZDUoUqmkvCEL4EPRDuOKWZ1hBg0OGi.ErAoTUKTakK.xUcQzI5YajGj2yKhs3BqLo7D7VZv3TmTtIOEx2Ry4EYvmONSkpUOVa3OQEXqpr74KSuHo98mKMrXVpVJ4oykL1JJ8cIXfJeXOd5ZPIRYNeBiP84YK56e4E8K2SJzUasDiZ0AJg4IPv3x5TQJJHCu8zC1CbzXmhh8.9R3oFABAu83mBscc8Mp3uGO6DiNAP5jp3PmTik50G2UAKjRDPuiq46JpRd8zNyGzbzzE607LrVKbR89SOBIlKFDavU+lmCOSrwG9OXiMJYi2jVxFu4rlIrTPGkT1DbMw5+Jor0uOw5flvekYM9CY8lXb66W9AbTSNDQY1fl2hSL2JybXi.Fwzbh2u32RJBOAu.cVLOkCkJyDQt6ztSAM.5INt.JFTgrJ6hTTaUor937UBH5a4zsjQmTJgB02k.avsTaoGQJToHA8FTn7us1rsbDoOjKzU7CkloZilj+CA8MK4S987R9jl+by+mb6ki4jurrI9o461adIt8yKb6EdalhBaySUPoKmqA5zgNmIEqqQO.KMp.QLTniFiNPqin83wrSEPyWZl10pKKVmKQBVYyfgOoPmm3RAzZy2S+1CsAiKpixkLyryPhCNWP.pwLyfa3vYvIxLp7f0+uMX4+VHdC+NXu14iwElCFga9uOvXw33W2uc+9vPUSA3R96+suel8l3FVbviXPCUHW0+w4C6BoGgbbFFHwBqw6s.l06VWGWidftPaT6h+BdJH1.W6UPrwXhjgrvT8KCccVvA9ulcG.SJ625TA9nKXMsAw1sAjyuds5jgv2d7xvP73uNzfX9xrwUPlMuBxbqqfL29JHyctBxb2qfL26cJC9Ye6jazCcWGfM5z11B1yqsBKZYyBI+MlWOMsA`

**Comment by christoph-hart** [comment]
I've fixed the first issue (child panel grabbing focus when you click on the parent).

But I can't change the second one (child panel losing focus when you click on the parent) because that is standard JUCE behaviour and will cause havoc if I tingle with this.
