### ISSUE TITLE
Hise crashes on "Create User Interface"

### ISSUE THREAD

**Issue by ustk** [christophhart/HISE#270]
### Forum Discussion
none

### Commit
[https://github.com/christophhart/HISE/commit/63f7a240857c8a269a7cc82d93009dda079966f0](https://github.com/christophhart/HISE/commit/63f7a240857c8a269a7cc82d93009dda079966f0)

OS: MacOS tested
HISE: YES
Compiled Project: n/a

### Description
Create a new project folder or just remove the initial interface after launch.
Create a new user interface -> instant crash

### Snippet
`n/a`

**Comment by davidhealey** [comment]
> Create a new user interface -> instant crash

What are the steps to do this? Just a MIDI processor called Interface and add the line Content.makeFrontInterface(600, 600)?

**Comment by ustk** [comment]
Nope, in fact it is when you click the "House" button in the ribbon

**Comment by davidhealey** [comment]
> Nope, in fact it is when you click the "House" button in the ribbon

Aha yes this bug has been there for a while.
