### ISSUE TITLE
DSP AHDSR curve/shape not showing

### ISSUE THREAD

**Issue by ustk** [christophhart/HISE#275]
### Commit
[https://github.com/christophhart/HISE/commit/63f7a240857c8a269a7cc82d93009dda079966f0](https://github.com/christophhart/HISE/commit/63f7a240857c8a269a7cc82d93009dda079966f0)

OS: MacOS tested
HISE: YES
Compiled Project: n/a

### Description
No shape is showing

![](https://i.imgur.com/PesAR6N.png)

**Comment by christoph-hart** [comment]
Fixed.
