### ISSUE TITLE
[feature request] Folder Access for "Program Files" on Win & "Applications" on macOS

### ISSUE THREAD

**Issue by beyhanklc** [christophhart/HISE#292]
On the FileSystem, the direct access for Documents, Downloads, AppData...etc. is great. Could you please add `FileSystem.Applications` feature for accessing:

"Applications" folder on macOS
"Program Files" folder on Windows

This is the missing puzzle of this great FileSystem features.

**Comment by davidhealey** [comment]
Shouldn't be too hard to do for anyone who wants to give it a try - https://docs.juce.com/master/classFile.html#a3e19cafabb03c5838160263a6e76313d

I think the constant is `globalApplicationsDirectory `

**Comment by beyhanklc** [comment]
Can you do that? I'd be appreciated for that my friend :)

**Comment by davidhealey** [comment]
I'll take a look

**Comment by davidhealey** [comment]
Done. I also added Temp folder location - remember to clean up after yourself ;)

**Comment by beyhanklc** [comment]
Wow! That was so fast! Thank you so much mate!
So I need to download your development branch to test it?

**Comment by davidhealey** [comment]
> So I need to download your development branch to test it?

That would probably be the simplest way. But be careful when you have two copies of HISE on one system

**Comment by beyhanklc** [comment]
I've just tested on macOS Monterey, it works great! I will try on the Windows tomorrow, Thank you again.
