### ISSUE TITLE
[feature request] label LAF

### ISSUE THREAD

**Issue by davidhealey** [christophhart/HISE#299]
Look and feel functions for drawing labels please.

**Comment by christoph-hart** [comment]
Why? You can customize pretty much the entire appearance with the script properties.

**Comment by davidhealey** [comment]
It was mainly so I can draw icons and shift the text input in from the edge. Currently I'm doing this by making the label invisible and drawing on the panel behind it. 

![image](https://user-images.githubusercontent.com/14021202/166910895-459d7246-2d0e-4012-ab29-88448a9632a9.png)

**Comment by christoph-hart** [comment]
Yes, I would not add that to the label, it's cleaner this way. I'll close it now.
