### ISSUE TITLE
getImageList doesn't work with full expansions until expansion has been loaded

### ISSUE THREAD

**Issue by davidhealey** [christophhart/HISE#306]
### Commit

https://github.com/christophhart/HISE/commit/a81d00bdfa9d531fb6389854282c64a01cbcde4c

### Conditions to reproduce the bug

OS: Linux
HISE: yes
Compiled Project: Haven't tested

### Problem Description

getImageList, getAudioFileList, getSampleMapList, etc. don't work with full expansions until after the expansion has been loaded. They do work with encrypted and file based expansions though.

I've been poking around in the source code but can't pinpoint the location where this issue is occurring.

**Comment by davidhealey** [comment]
Well I think I might have fixed it. @christoph-hart Please tell me if this is an acceptable solution and if it is I'll make a pull request - https://github.com/davidhealey/HISE/commit/0e66047a5218e1bcd77b5fcfe1eee26d7d48f9b4

**Comment by christoph-hart** [comment]
I think we solved that one, if not let me know...

**Comment by davidhealey** [comment]
We didn't make the expansion's entire image list available. The solution in my case is to name the image `Icon.png` which is available before the expansion has been loaded, but it doesn't show up in the image list so to access it you need to use the expansion's wildcard - which I think is a fine solution.
