### ISSUE TITLE
SFZ Imports do not work for most SFZs - Missing Parent

### ISSUE THREAD

**Issue by lunacyaudio** [christophhart/HISE#311]
HISE only allows SFZ imports for SFZ files with `<global>` in the file, otherwise it will throw the error `no valid parent for group`. Most SFZ files do not have this parent in the file, so they are unusable without adding the parent manually. 

Here is an SFZ file which imports properly into HISE: https://www.pianobook.co.uk/packs/halfsize-nylon-guitar-ds/
Here is an SFZ file that won't import without manually adding `<global>` to the file: https://www.pianobook.co.uk/packs/the-bells-of-woodland-heights/

Suggestion: Add `<global>` automatically to any imported SFZ which is missing it.

**Comment by christoph-hart** [comment]
This is fixed now. Let me know if you find other SFZ files that don't load...

**Comment by lunacyaudio** [comment]
I've tested this a bit more and noticed it still has some issues with certain SFZ files. Here's an example of one which throws the error `no valid parent for group`:
https://www.pianobook.co.uk/packs/kawai-old-toy-piano/

It will only work if you add a `<group>` tag

Here is another SFZ which will only work if you add a `global` tag to the top of the file:

https://www.pianobook.co.uk/packs/the-omni-master-key/

**Comment by christoph-hart** [comment]
Alright, those are fixed too. I'll keep this open for the case that there are more SFZ glitches (but I think now all missing tags (global, group, control) are handled correctly).
