### ISSUE TITLE
LayoutMode Delete Button is a bit overambitious 

### ISSUE THREAD

**Issue by qdr** [christophhart/HISE#32]
![bug 001](https://user-images.githubusercontent.com/8782378/27496344-e15cddfc-5855-11e7-8278-155ec2f2b7f4.gif)
Critical because the bug manipulates the project structure in %APPDATA%. Depending on the autosave settings, HISE doesnt start anymore at all.

**Expected result / fix**
- remove kill switch
- make it accessible only in custom workspace

-------
Standalone
latest dev
Win7 / VS15

**Comment by christophhart** [comment]
Drive-by fixed with the floating window update
