### ISSUE TITLE
Compiling develop branch on Fedora: ‘exchange’ is not a member of ‘std’

### ISSUE THREAD

**Issue by SimonCDalzell** [christophhart/HISE#321]
The title pretty much covers it. I'm trying to compile the develop branch and run into this issue once it gets to compiling include_juce_gui_basics.cpp. I was able to compile it within the last month but perhaps something changed.

`JUCE/modules/juce_gui_basics/misc/juce_DropShadower.cpp:134:46: error: ‘exchange’ is not a member of ‘std’
  134 |         const auto lastSeenComponents = std::exchange (observedComponents, [&]`

gcc is version 12.0.1 and the makefile says ++17. I did the usual googling attempts but I'm not sure where to go from here.

**Comment by davidhealey** [comment]
Did you run `make clean` before compiling?

**Comment by SimonCDalzell** [comment]
I added #include <utility> in juce_gui_basics.cpp which seems to have solved it. I have no idea if that's the "correct" way to fix it but I'll take it for now!
