### ISSUE TITLE
Crash in compiled plugin when using "addGlobalModulator" on HardcodedMasterFX

### ISSUE THREAD

**Issue by lunacyaudio** [christophhart/HISE#334]
Hi there! Playing around with scriptnode modulation a bit more and noticed that any compiled HISE plugin will crash if trying to use `addGlobalModulator` on a given HardcodedMasterFX module. The crash only occurs in the compiled plugin, not within HISE. Symbolicated Mac crash report attached for example below.

Here is a HISE snippet with a simple button for assigning a global modulator to a simple scriptnode Pan module:

`HiseSnippet 1286.3oc6Y02aaTCF2WRLzFdaST9GDHcp+UpnDkz10M.gHzzlQDMsQjtBHjXy8NmdV8N6CeNsDg1mA9pwGE9F.O9tK4bRSSSy51ZfcRKp1OOO1+tmW94GeqsT3PihDRj0xG0OjhrdWbm9bkWcOBiiZtKxZIbaIMhpP6zOjDEQcQVV4erVp0xEPwO+82rCwmvcnYSgPGKXNz8YALU1rsq88Le+FDW5Qr.Cs2pVSGAutvWzCPRdbETHw4LxozCHZ0xgQVu0dtLkP1QQTzHjUgcDt863Itfmn+wrH1I9T8fpnNvBkLcCguqFw5YQ08X9tsG7FGgPV31Yu+4Sd+WA2h4xFNele3dwBryrvzeXkaT3keD3U0DdULf2DfjkAjJj.o6i63HYgpLIZ77N3lbEU1k.tcSnjnKJmWNbcAnAWUNfbFsgDFLzhRaWox51vOq8UEAOejx9bhzNjvs+Z633e4Sop851k5nJsZaBe0w0qkv0TUXXOeB3.h0FFMpA623vgZT8JrCzwNSoq19MlE62PaewhLtOiSs61i6nXBtMrfF1ncORgeIGQPnfCNp0gMyuGcsh+Qwkg2wxDW2G6KNg3msMfWaDvrdpyPClltkVC11mC67.OOLa8AqdoUM27UWqbjVXLDpS78OAx3KMQ.F+pTz3k3.ghdHuTLNK97h1iKpa2IJKc47oxIJVWRJmlgk38BNgJM8RZEg7zQS9wWcxuYsoShOxPQAuImoNLjxupJVTpiE9qmzbWhhnqXRmCzKjJULMDr1kdNP+jT+rLdWZzYJQXrtoQCj0aqhk99oUW6zSoDbDyUOkYT.86YDU+bs9YC90ZWvbUdCmv9Y07nrS8LH7NnVD4bZSdJEJTdhtb8MvrLLhaP2n4XSE.ggQpw00w7HlpuIG73bPElMNnoSQNqv8931Lki2jwatIfWHv8xFuoL5uGNgHKCrEvM9ooReWX1xfyfx0RkiSvxGg+Nhz0Q.lY2hDArw1.TzXBiAhyQ.0AT0EB4YCDo+mYzN+LehS0oehyRyXH9CvsqZ+hjPd6bn3RIP7SvITyZVqiIRFgaTwl12RLy70iymDQOhDCDsBmCbHIJGOYLIitCDfkgSiYDQVqmt4YG3XqIg.OEUV8KG8jLzMvML8HEZ1CTaXuvvb.ncyEJzt0BEZevBEZ2dgBsObgBsO5N.Z+AQOEieZKhRxf1pvGzKnCbmOGJfTfd0W28nUNcedIiqnGqATGJ2Mdv+.OoBqpGakJr5.gnKeVwGiGqM9gj0w9lOcZr4S4Zu+0rds2vY9Zuiep9MtQjIdM2Burtl6qzT3O7Rgona0z3aPmc4Lf78RfLFCG6m5AGqAfqEj6vBE9DoVdCI825Q4NCj+rtcWolNyoYVhWs+r1OB2pnqPFjdAmgqz9zSg8zblinvEdf6K6Xlj1IPHTdPg3n4iqTaegHbOttuGWyEosGIResx36vXrLvxdjHoO159BmyLEVuWjRDL.nwsP0QQCS5m5WvauUY3o6mo+8KpC+r4g2Niu852Zjv7zyL0Q7ggV6YpqyWy0RZDOLY6NBhutRoMdgJkfmkdSozaJk9eQozb+sZx+enuUycrFSeUrGADGo3oNIev13utS7Lv6MO9+Jkkwszisqhh+HtZx1JkqfBfd9dpii1c+4f+Yx1rwbXylygMaMG17f4vlsmCad3bXyilpM51s+1d.+dRoHLQ68RX1sFd7gUdz+dWOvoK` 

[Modulator Test Debug_2022-06-15-123828_Casey-Kolbs-Mac-Pro-3.pdf]
(https://github.com/christophhart/HISE/files/8912487/Modulator.Test.Debug_2022-06-15-123828_Casey-Kolbs-Mac-Pro-3.pdf)

**Comment by christoph-hart** [comment]
Have you added the preprocessor that changes the amount of modulation slots into the `ExtraDefinitions` property? I can imagine that if you compile HISE with modulation slots, but then export a plugin without those slots, it will crash because it can't find the slots.

**Comment by lunacyaudio** [comment]
When I add that preprocessor to the plugin, it crashes immediately when trying to open the compiled version. Here's the symbolicated crash report for that:

[CUBE Debug_2022-06-17-095408_Casey-Kolbs-Mac-Pro-3.pdf](https://github.com/christophhart/HISE/files/8929369/CUBE.Debug_2022-06-17-095408_Casey-Kolbs-Mac-Pro-3.pdf)
