### ISSUE TITLE
Code Editor Stuck

### ISSUE THREAD

**Issue by JewishLewish** [christophhart/HISE#338]
![image](https://user-images.githubusercontent.com/65754609/178340742-c334ab7a-5036-4174-8242-a625f82d64ca.png)

I tried "folding" and "expanding" however it doesn't make it bigger. I can't "move the tab to the side" to enlarge it because I can't grasp onto anything. 
I tried to uninstall and install again but it didn't work.

**Comment by davidhealey** [comment]
Looks like you're using a really old version of HISE. You should build the latest version from the develop branch.

**Comment by davidhealey** [comment]
The last binary release is years old and shouldn't be used. The develop branch is here on github - https://github.com/christophhart/HISE/tree/develop

I have some videos on YouTube showing how to build it for different OS. The most recent video I made about this was for Windows.

**Comment by davidhealey** [comment]
You can use VS2019 to build HISE. That error is to do with IPP. My video explains it.

**Comment by davidhealey** [comment]
@JewishLewish I think you can close this one now.
