### ISSUE TITLE
[FileNameTokenParser] The combination of Velocity Range + Number Range throws exception

### ISSUE THREAD

**Issue by qdr** [christophhart/HISE#35]
![bug 004](https://user-images.githubusercontent.com/8782378/27508470-fee58654-58e5-11e7-9564-c52f4ce6ee80.gif)
## Expected Behavior

- return false format

## Current Behavior

- breaks
- in 1.0 no samples are shown

## Possible Solution

- throw error message / false format

-----
Standalone
latest dev
Win7 / VS15

**Comment by christophhart** [comment]
- should be covered by in place docs
