### ISSUE TITLE
Cannot assign the same MIDI CC to two different controls

### ISSUE THREAD

**Issue by lunacyaudio** [christophhart/HISE#375]
Steps to reproduce:

1. Right-click on an interface control and assign it to any MIDI CC.
2. Assign another control to the same MIDI CC.
3. Adjust MIDI CC data  and observe that only first assigned control will move with incoming CC data. 

This is possibly related to this commit: https://github.com/christophhart/HISE/commit/2549bd02e4c55eb55041981e9a71c7e14e1147ff

@davidhealey

**Comment by davidhealey** [comment]
Yes I'm almost positive that is the commit. It is certainly one from around that date because I tested all the ones that would build :)

**Comment by davidhealey** [comment]
@lunacyaudio This can be closed now, fix is here - https://github.com/christophhart/HISE/commit/fcad7d6f02284a19f894921fe8767222c7f02239

**Comment by lunacyaudio** [comment]
@davidhealey Great!
