### ISSUE TITLE
[Feature Request] Method To Read Metadata in wav file.

### ISSUE THREAD

**Issue by itsnestee** [christophhart/HISE#385]
Hello. 

Would be awesome to get a method that directly reads each wav file metadata(loop points) when selecting the samples folder using the File System API.

**Comment by christoph-hart** [comment]
There's a API method called `loadAudioMetadata` which extracts all metadata found in the audio file. This will include information about loop points, but it's your responsibility to parse that information correctly (the syntax might be different for AIFF files vs. WAV files, etc).

Here's a wavefile metadata:

```json
{
  "SampleRate": 44100.0,
  "NumChannels": 2,
  "NumSamples": 529200,
  "BitDepth": 16,
  "Format": "WAV file",
  "File": "C:\\Users\\chris\\Desktop\\test_signals\\guitarloop.wav",
  "Metadata": {
    "Manufacturer": "0",
    "Product": "0",
    "SamplePeriod": "0",
    "MidiUnityNote": "60",
    "MidiPitchFraction": "0",
    "SmpteFormat": "0",
    "SmpteOffset": "0",
    "NumSampleLoops": "1",
    "SamplerData": "0",
    "Loop0Identifier": "0",
    "Loop0Type": "0",
    "Loop0Start": "264704",
    "Loop0End": "529199",
    "Loop0Fraction": "0",
    "Loop0PlayCount": "0",
    "MetaDataSource": "WAV"
  }
}
```
