### ISSUE TITLE
MIDI Player loop, loop points & track length

### ISSUE THREAD

**Issue by ustk** [christophhart/HISE#391]
### Forum Discussion
[https://forum.hise.audio/topic/7311/midi-player-transport-bugs-info-requests/10](https://forum.hise.audio/topic/7311/midi-player-transport-bugs-info-requests/10)

### Commit
Actual

### Description
- The MIDI Loop button doesn't seem to do what it is supposed to.
- Once it loops for the first time, the first beat never plays anymore, shifting the sequence (the first beat is missed, or the last, depending on the loop being enabled or not...)
- The track length is derived from the last note off, instead of the End Of Track event.

**Comment by christoph-hart** [comment]
I've fixed the LoopEnabled button issue with 88dce1548, but the loop end not being set to the bar end is not a bug but a feature - the MIDI files often don't contain this information (and I assume that most DAWs just simply round it up to the last bar or quarter beat or whatever).

I don't want to change the default behaviour for backwards compatibility, but you can just use this snippet to assign a callback to any sequence update that ensures that it's always a round number of bars:

```js
const var MIDIPlayer1 = Synth.getMidiPlayer("MIDI Player1");

MIDIPlayer1.setSequenceCallback(function(mp)
{
	var s = mp.getTimeSignature();
	
	if(isDefined(s))
	{
		s.NumBars = Math.ceil(s.NumBars);
		mp.setTimeSignature(s);
	}
});
```
