### ISSUE TITLE
 [bug] plugin either skips a note event  or triggers a sustain note that can't be stopped (FL Studio)

### ISSUE THREAD

**Issue by engNesta** [christophhart/HISE#401]
When I load the plugin in FL Studio and write some notes in the piano roll, the plugin sometimes either skips a note or triggers a sustain note that can't be stopped.

**Comment by davidhealey** [comment]
Which OS?
Which version of FL Studio?
Which commit of HISE?
Do you have a snippet and a MIDI file that can be used to recreate the issue?

**Comment by christoph-hart** [comment]
Should be fixed now with commit f6da45d0d52db9f3758c2ef733eb7f2f3f5edd12
