### ISSUE TITLE
MacOS 11 version requirement

### ISSUE THREAD

**Issue by QrchackOfficial** [christophhart/HISE#404]
Hi,

I've just got around to checking HISE again after a while of knowing about it but not trying it for anything more involved. Looks like between 3.0.3 and 3.5.0 you broke compatibility for my 10.14 Mojave system by specifying LSMinimumSystemVersion at 11.0, compared to 10.9 in 3.0.3. What is the rationale for such a drastic change (we're talking dropping support for anything from Mavericks to Catalina, that's 2013 to 2019 in terms of OS versions)?

README of JUCE (https://github.com/juce-framework/JUCE) specifies:
> ### Deployment Targets
> macOS: macOS 10.9

So I don't believe this is an upstream requirement.

**Comment by christoph-hart** [comment]
Yeah that was a oversight from me - apparently the new macOS SDKs have deprecated everything since 10.13 and I was a bit overambitious (actually I didn't realize that 11.0 is not the direct successor of 10.9 :)

I've changed the minimum version to 10.13 (that would be Catalina IIRC), which should be plenty enough.

**Comment by christoph-hart** [comment]
Also this is just for HISE and since you can't compile native ARM binaries with anything < Big Sur, there's no point supporting much older OS versions anyway.

The compiled projects should still go down to 10.9.

**Comment by christoph-hart** [comment]
Also this is just for HISE and since you can't compile native ARM binaries with anything < Big Sur, there's no point supporting much older OS versions anyway.

The compiled projects should still go down to 10.9.

**Comment by QrchackOfficial** [comment]
Thanks. 10.13 is actually High Sierra which is not a bad place to be in. This includes 2009 iMacs with Core 2 Duo, but also 2011 iMacs with 2nd gen Core, 2011 Macbook Airs and Pros with 2nd gen Core. It's also the last version of macOS to support NVIDIA GPUs of the GTX 10xx family, making it still relevant for Hackintosh users.

10.14 is Mojave and there you have 2012 Mac Pro cheesegraters (the last models before trashcan Mac Pro).

And 10.15 is Catalina where we have 2013 iMac with 4th gen Core, 2012 Macbook Air and 2012-2013 Macbook Pro, as well as 2012 Mac Mini.

In my case it's Mojave on Hackintosh with 8th gen i7, and the important reason to stay pre-Catalina is Mojave lets you keep using 32-bit applications, of which I have a fair amount - we're talking legacy audio software that might be 64-bit but the authorization software is 32-bit. Sibelius is one example. So thanks a ton for reverting that, eagerly awaiting an official build, might build it myself in the meantime.

**Comment by christoph-hart** [comment]
yeah, don't hold your breath for a new build, will take another few weeks until I'll bump the version to 3.5.1

**Comment by QrchackOfficial** [comment]
This is still present in standalone as of 3.6.0:
https://github.com/christophhart/HISE/blob/3235dacd40422bd91d0bb19b7bc115e78b34ed61/projects/standalone/HISE%20Standalone.jucer#L56

Working flawlessly as a plugin on 10.14 Mojave though. Just the standalone.
