### ISSUE TITLE
[bug] ScriptNode - Loading an SVF filter into a multi that already contains two instances of an effect (one for each channel) crashes HISE

### ISSUE THREAD

**Issue by aaronventure** [christophhart/HISE#405]
Master branch.

1. Add multi in a DSP Network
2. Load anything into it. Can be a filter as well. Alt+Drag to the side to copy to the other channel
3. Try to add the SVF filter under the existing effect in one side of the multi

**Comment by christoph-hart** [comment]
yup that has been on my list for quite some time. It will now use the error reporting system in scriptnode to complain about too many channels instead of crashing.
