### ISSUE TITLE
[bug] ScriptNode - Alt+Drag duplicating a multi with FX that have controls linked to a parameter controller doesn't copy the links and leaves the controls unavailable

### ISSUE THREAD

**Issue by aaronventure** [christophhart/HISE#406]
Master branch. Sometimes it even crashes HISE.

1. Create multi, add two instances of an effect to it, one for each channel
2. Create a parameter for controlling a knob and link it to the the knobs on both FX
3. Alt+Drag the multi below

**Comment by davidhealey** [comment]
I'm not getting a crash here on the timestretch branch. Let me know if I've not recreated the scenario correctly

![Peek 2023-08-06 15-53](https://github.com/christophhart/HISE/assets/14021202/1d8b7fbf-76e4-4fac-a29a-e768be31d3fc)

**Comment by christoph-hart** [comment]
I've fixed it so that the node parameters will not get deactivated, but they still won't copy the connection to external parameters / modulation sources. This would be rather complicated to implement and prone to edge cases.

**Comment by aaronventure** [comment]
Alright, cool. Them getting deactivated was the bigger issue as you'd have to manually re-add them all. Reconnecting manually will take a bit but it's not a deal breaker. Maybe it's a better idea to connect to the parameter inside the multi anyway.

**Comment by aaronventure** [comment]
> I'm not getting a crash here on the timestretch branch. Let me know if I've not recreated the scenario correctly
> 
> ![Peek 2023-08-06 15-53](https://user-images.githubusercontent.com/14021202/258649753-1d8b7fbf-76e4-4fac-a29a-e768be31d3fc.gif)

Yeah, that's about right. Can't really figure out what makes it crash, but occasionally and randomly it does.

**Comment by davidhealey** [comment]
Maybe a clone container would work for your purpose, so you don't have to reconnect things
