### ISSUE TITLE
[Bug] Deleting an effect slot after its child slot is trashed crashes HISE

### ISSUE THREAD

**Issue by aaronventure** [christophhart/HISE#407]
commit e77f723b0cf918e78dfb9fbabe74fd0e26ebd112

1. Add "Effect Slot". 
2. Click on the trash icon of the child so its icon turns grey
3. Click on the trash icon of the parent Effect Slot.

![hise effect slot crash](https://github.com/christophhart/HISE/assets/141569073/2bcb20d6-bba2-402b-88ee-04a0b2dfae1f)

**Comment by christoph-hart** [comment]
Thanks, that's precisely the stuff that I don't see anymore and requires a pair of fresh eyes. Fixed now on `feature/time_stretch`
