### ISSUE TITLE
[Bug] Trying to open script tab of a .glsl script with undefined iChannel0 variable crashes HISE

### ISSUE THREAD

**Issue by aaronventure** [christophhart/HISE#409]
[ChromaticAberration.zip](https://github.com/christophhart/HISE/files/12291089/ChromaticAberration.zip)

1. Create new project
2. Extract the ChromaticAberration.glsl into your Sctipts directory. 

then load the snippet 

`HiseSnippet 779.3ocsUs0aSCCE1tqYhFtHlD+.h5SoRkpTXLPZBw15EnBVWEcLPBgl7bbarVpcji6FUn8elW3Y33jzlzspAqRzGpx4xmOe9juyICTRJKNVpP3JGOKhgvOvZ3LgNnU.gKP8ZivOx5PRrlobRccvrHRbLyGgwa7ViCbkxnje+7MGPBIBJK2EBchjSYefOgqy8NXu2yCC6R7YGymTH6s2qGUJZICkSA9rgkGJhPOmLl0mXRqjEBuYGetVpFpIZVLjyAR+YCCjWJRy+DdL+rPlwnIZHbPotQsB3g9CleWiQHb4A427MRu4Ow5PtOeg+7NviSB3jinXO.W51nTy6.kvEnT4TJsk0PphGoyiX3y8s5IfWHiHPqtHURyEU5WXqVRHCgtwDx4rtJvXAB2c77p6.+UaWaancGqctfnbhDgm1WxiYNu1YNXhu+.hfE5VcQzp0c.zd0rW3oQLS6V8RtuN.B1zK4fuVz.FebfNObg5FG.x.00qLUwft4vjXtUaEnjSHZNc+yXJE7fTT0bJ1KWmAv6K8GkS0bAyczTA0jn63Z1+vtx3FjnnvYYmXghV24qdI2Ic.OtwXl9ylahasbGuKg7t09FTxqps67C1QJ5K0riDtIEv9JamqGZznUFybIUxvPfHqJrYlPca.cESm.Mh5P+KbJaQhfnYYk3l+aJQZZOuPhRQOAWeTDKytqLz2nvLOeScKJ6kF7zm50lnIFoblOHuHlRyMzA2lcArKHUXWwpMK9bsLB1FbCUOLuI8mFRzKODZ11jE.5GKo7MpaQLWOq31n6vjo2sNY9uRwsrFv0zfUywRqfiPm5+AGy1m8PqNiFwn5bBV1p6WV2kW+kxmN2M9PhVw+NBa0e5jgvZbJCpt.1g.GtEtjQsjZ6YrMcfgLgehwugeYAaZrwYAaNOHZBgpjmRSmBLaLuWhGfShjOPTA9REX6zDkLY.3r7Z3gl.KuOkRMW+mBB3Ui4YqAlmuFX1dMv7h0.yNqAlWtFXd0shw7cy8mpS1dCiCfiAcRVQfwcDDPYknBQ+A7O4cIA`

Hise will throw an error about the undefined variable iChannel0. 

3. Attempt to open the script in the script editor. 
4. RIP

If you remove 

```
pnl_Noise.setPaintRoutine(function(g)
{
	g.applyShader(shaderNoise, [0, 0, this.getWidth(), this.getHeight()]);
});
```

and then compile, same happens when you attempt to open the script tab.

However, if you delete these 4 lines, save the project, close and reopen HISE, you can access the script via the script tab normally and it won't crash.

`HiseSnippet 767.3ocsU01aSCCD1tsYhFXHlD+.h5mZkFSov3EoIDaqufpf0EQFS7sIOG2EqkXG43rQEB98xG4e.bNosIczMgpX8CU12yc1O9tm6hmRRYooREB27joILD9QV9SE5vdgDt.MpOB+XqiHoZlxovzgSSHoor.DFW+8FC3lMP4+906NjDQDTVoID5TImx9HOlqKs5s+G3QQCIArS3wU7d28GQkhdxHYFvm5VtnDB8RxErwDia0rP3MFDv0RkulnYoHbiCkAS8CkWKJ7+TdJ+7HlYSWjObPElGJiBLL1XE0KjGE3M+cmhfSwqLKTuHK7Tqi3A7E1KyFOIGvoLhp4CbskoW8knW2pzysB8VAkvUnTiBJskkOUwSzkHF97PqQBn3Lg.o8pTovWTsefs5IAOD5chIWxFpfMKhn8qbc21A9qyd11PpOU6bEQ4jHhNarjmxbdqy7fIAAdDAKpcqEns11Ah1si8BK6jxzsacMOPGBfccyO3afFx3WDpKgqbuogfjPcyalpXP1zOGqcqdgJYLQyoGbNSofERQqN6MISPMKcjhwRM6XQ6N1eyto82sctIzjIqDybaJYTDbGqB1HTU2UfsEYw.i1FdHQYrENBUukkDV2tjnphkV73q3nTLRv0GmvD2lNFMKiAq97n9DMwnilYC7KgozbCEv8YWAMkEpplV8YoWpkI49FmHElS.ugNGcy4ZNSoGwCL5sE0SzWgmC1z3Nc9h7RObna7y5EszEU6pVP+sxF5ojAYQD8xMZloKy.fT8RpaiBVjx0SqN84+V22+JE2xxiqogqli0VAGgBx8AGmMyZSqASlvn5RB1vZ3WteFPg9jLSyEWbDQq3Fcv3rXeXrMkA2t.DKFoNtlQTVr2ctDwmIBx27a32Lvtl83YfcmChhITk7LZQClYp3Cxs.bRj+AglvWlf8NcQ4McPbVt63hhgAzmQolm+yf9jUGyyWiXdwZDytqQLubMh4UqQLudMh4M2YLluMdPlNeBMzN.F7FjOIBiGHHfxJWEh9Cb32K0.`

e77f723b0cf918e78dfb9fbabe74fd0e26ebd112

**Comment by christoph-hart** [comment]
Oh that was a trivial error but I guess I haven't used the GLSL editor for a while.

Just FYI, you can't use textures in the Fragment shader in HISE so whenever you see something like iChannel0 on shadertoy.com, you need to continue browsing...
