### ISSUE TITLE
[Bug] Ctrl + Backspace jumps all over the place doing weird stuff, when it should delete the previous word (and a spacebar that's after it, if any)

### ISSUE THREAD

**Issue by aaronventure** [christophhart/HISE#411]
In Script Editor.

f695f0cb22de5c392d57b3ecc16492d4293986b8

Win 11 Pro ,Version 10.0.22621 Build 22621

**Comment by christoph-hart** [comment]
Interesting, I've mapped Ctrl+Backspace to "Undo goto" (this is taken from Xcode) but I'm probably the only one using this so I've remapped it to Cmd+F12 and restored the Ctrl+Backspace from Sublime et al.

**Comment by aaronventure** [comment]
I just found it weird that it did delete last word in all other places except the script editor, but ctrl + del deleted the word in front properly as expected.
