### ISSUE TITLE
[Bug/QoL] Keep selection when adding "([{ keeps autocomplete placeholder parameters

### ISSUE THREAD

**Issue by aaronventure** [christophhart/HISE#412]
Pinging back on the addition from 07435e365d1df64a9b032d70a8e1c5d17c0cd21e, when calling something and using autocomplete to speed things up, the first parameter gets highlighted, and if it's, e.g. supposed to be a string, I will automatically press " in order to type the string, which will now encase the placeholder stringVar into "stringVar". 

Ideally, in cases of using "([{ on placeholder parameters that populate function parentheses from autocomplete, it should behave as it did previously, replacing these entirely.

This is just a step (backspace) away so it might be a trivial thing to complain about, but introducing the feature (that I) requested caused the workflow in _this_ regard to take a step back, which someone may take issue with, so I feel like I should at least mention this. 

![hise keep placeholder](https://github.com/christophhart/HISE/assets/141569073/0ba0bd8f-a15c-46b6-a562-dc2f10e1aeaf)

**Comment by davidhealey** [comment]
Oh yeah this is super annoying now :)

**Comment by christoph-hart** [comment]
Should be fixed now.

![autocomplete2](https://github.com/christophhart/HISE/assets/6277426/14930128-c9f5-4745-9275-da98338a4786)
