### ISSUE TITLE
[Bug] Clicking the X in the corner a floating tile goniometer in the popup window interface after disabling the component crashes HISE

### ISSUE THREAD

**Issue by aaronventure** [christophhart/HISE#415]
1. Add Floating tile.
2. Add Analyser FX. Make it a goniometer. 
3. Connect it to the floating tile. 
4. Open popup window View > Add floating window. Add Script Content to show your plugin interface.
5. Focus script editor and hit F5 to comple. 
6. Little X shows up in the top right corner of the interface in the floating in the popup window
7. Click X. Nothing happens. 
8. Disable the floating tile in the interface editor by clicking on it and setting its "enable" parameter to off. 
9. Focus script, hit F5 to compile. The panel in the popup goes red when hovering the X.
10. Click the little X in the interface. Not the one in the popup window corner but the plugin interface corner in the popup window.
11. I have become death, destroyer of intricate scripting editor tab setups.

`HiseSnippet 1159.3oc2W0jaaaDEdnkm.KYmllhDztjvnKb.bCDkSSKZWDYaI4JzHaAK23rKXL4SRCL4LDjCssZP1zU93ziPNB8HziPuAsugT+LzgQPUn0MoZggmu27H+d+8MC6FIcg3XYDwp7IiBAh0FzdiDpg6OjwEj1MHVeBsCKVAQ1YP6MJjEGCdDKqRGnArJuJI82e7r8X9LgKLChPdgj6BOmGvUyP6V+G499sXdvI7.ic+j5sckh8k9xDjOknUIgL2yYCfCY5ssBkXcmldbkLpmhofXh0p6I8F0an7RQ19eAOlelOnW3P5gOnL3VReOMi0nj8Gx885NItiIDKZ2YYgRYYgGP6v83SwmkM9zTC1y7vLeXsRd5UJG8bLoWUC5U.krLnzpYT59zdtQ7P0LKZ9rNss.KN8YXZ2jJY6kX8V59RbCB0iCXmCshvEScXqmVs5113edz22OQ3p3RgsTbnTAGI15QUdckxUdSE6aZpe+BsoeMQReeHpPy5Jcz7bbKQRvYPz11Wv7SfoaDC+74T56OmZVxcyhZiMJEsEb0Qgf380HPFmpv+6mZ2foX5BwXLbegPjhqofUC3BrqNqrTl1.hOWICwFz8kAgRg9IXstJ05cmTzXBvmvwRyZzz+2gbk4XxHyEmMXxLP467m3OMFWAAyPQfafVyDVAWod2GwkbO0voum29K0GB7ACUlHffg4xzFHhQvrgZ7PQVvzxWxTbwfS3XdWGS2iZBMuPaA3PZh2pC80Urs2bZ4os2lem8lGHEbY.f8uats1bagGbEZnZ5JbL2Wd4oxnyiQgC.w6y7igJuYRgMqhcO5tIdb4tBl+nXHJW5dmc1ofz80WecQo6FMZTP5dRnRd2QXT7P5k3yT4UTzxniMfiD4Fi0yphXtZjoL6+XxLKJEuOsKW4NrXNtRAbDGb92fiiEmuKsY+9fqZFAWk15k2BJwzr2eE5zdG8KeC5r1xbjXuDjlQ83+rwYb+Z8tQn5Ab4X0iIIr5VkVXF6L+D1wxD8nXGlJhiShzCSB5g8lt.luDnziVD0ZEsbW15p50ZNzCDdoKzJFiM5nWaM1nyDilEkGlEIqSOkcAjd2gzrxCSW2WFEXe.HfHcGkybt8vusn2dHbgu8vQtJjBmDwDwgxXTWx3IeCa0Ls0.TIh7aOCJ2tzgWKL7L12Z0m.VyDDE7y8vv04dRc3FBl+9yZlJB2Cvnw6nXWLX04NSAftInr1oZoTGSGmAWyD9GXQdXcwM23Yo4cQJmk7hT24CtKR8QfHbNElxS3XOdPnOzTbA3iW7HkieFdSi9rDe0Dz7iScjBY3PTIJWg9X.UAFL.x0+TX.sqRg21dFxCpeL3CrXiQrur9y4BfEg4IXIyEN+su2ag0quflQWasFf8GuGdV5+0Gdt3SenD3G1UwOmhRw0rSKk1+2TKuMNW+13cDvbijuxM6y9zC8qkhfwsH867KS6nWa6PR+TPzOZ0GWkDfGW7JWWc+5Wgm9TrO0VBe1YI74IKgOe8R3ySWBe9lkvmuct9nOod2DkLHqmGA51L6yzrZZ7Ei+EM9QyzB`

Here's a snippet to skip the first 3 steps. Proceed from 4 onward. 

![x gon give it to ya](https://github.com/christophhart/HISE/assets/141569073/aa6a533c-7930-4f38-9b09-cee837a1ebf6)

3235dacd40422bd91d0bb19b7bc115e78b34ed61

**Comment by christoph-hart** [comment]
The close button had no reason to appear in the first place anyway, so I just made sure it doesn't show up so that the destroyer of intricate scripting editor setups will stay lurking in the eternal darkness to never walk on the face of earth again.

**Comment by aaronventure** [comment]
May the universe heed your words.
