### ISSUE TITLE
[Bug] Right-clicking effect_slot_empty crashes HISE

### ISSUE THREAD

**Issue by aaronventure** [christophhart/HISE#416]
1. Create Effect slot FX
2. Right click on the effect_slot_empty child

![hise effect slot](https://github.com/christophhart/HISE/assets/141569073/a3a633ce-cf23-44c7-862c-bc1193274dee)

3235dacd40422bd91d0bb19b7bc115e78b34ed61

**Comment by christoph-hart** [comment]
should be fixed
