### ISSUE TITLE
[API] Array.length not documented in the API page

### ISSUE THREAD

**Issue by aaronventure** [christophhart/HISE#417]

**Comment by davidhealey** [comment]
There are a few of these "secret" function, like `object.clone`

**Comment by aaronventure** [comment]
or trace, which is like toString

**Comment by aaronventure** [comment]
The thing is, I found out about it in the docs in the introductory page to Hisescript, and then no mention again anywhere.

**Comment by davidhealey** [comment]
`typeof` is another one you might find useful.

**Comment by christoph-hart** [comment]
Just wanted to add this, when I realized it's already there (literally in the first coding example). I've added red arrows so it's harder to overlook:

![image](https://github.com/christophhart/HISE/assets/6277426/c3abef0e-df1e-48fb-a578-60db8c42cdb7)

**Comment by davidhealey** [comment]
@christoph-hart I think he meant the API tab inside HISE

![image](https://github.com/christophhart/HISE/assets/14021202/2188de3c-7fc3-4dbb-a291-c557e9280a52)

**Comment by aaronventure** [comment]
Yeah, that docs example was the only place I found any mention of this, so I reported it not being in the HISE's API panel.
