### ISSUE TITLE
[Bug/QoL] Text wrapping doesn't work with backticks in the markdown documentation editor

### ISSUE THREAD

**Issue by aaronventure** [christophhart/HISE#418]
If I highlight something in the docs markdown editor and hit the backtick, it replaces the highlighted text instead of wrapping it. 

I'd also like to suggest that hitting a backtick with multiple lines selected wraps the lines in triple backticks.

**Comment by christoph-hart** [comment]
The problem with the backtick is that it's a [dead key](https://en.wikipedia.org/wiki/Dead_key) so the usual keystroke logic doesn't apply here and it's not important enough to go down the rabbit hole of implementing a custom solution for this key.
