### ISSUE TITLE
[Bug] Opening a Scriptnode workspace while that DSP network is open in a popup window freezes HISE

### ISSUE THREAD

**Issue by aaronventure** [christophhart/HISE#421]
1. Make DSP network
2. Open the interface workspace or something else
3. Create popup of the dsp network graph
4. Open the DSP network workspace 

HISE window becomes completely unresponsive. The popup is also unresponsive. Unable to close it via the exit icon, the whole window freezes (both HISE and the popup). After some time, it will execute every mouse action that you "queued" in order, then freeze again. If one of these was to switch to a different workspace, HISE will unfreeze. 

Win 11, 15f6e578969fc8a34630e2297256fb0ef5178373

![hise popup network freeze](https://github.com/christophhart/HISE/assets/141569073/619adc33-f2c1-4a92-877c-63be990d1685)

**Comment by christoph-hart** [comment]
Does the complexity of the network have an impact on this (so does the freezing also happen with a very simple network)?

It could just be that the complexity of the DSP network graph is too high to show it twice, then I could make a safeguard that prevents having two instances of the graph visible.

**Comment by aaronventure** [comment]
I'm on fe6982e9ef42c474d92e66916fae4561f89f9de0 now and you seem to be right, it does. At least with smaller things like 2 oscillators back to back, no issues. I used convolution reverbs in the example in the OP (16 of them in a multi), so I don't know if its peak display is intensive and rendering them all twice would've been crazy.
