### ISSUE TITLE
How to copy an array

### ISSUE THREAD

**Issue by twiddlecoding** [christophhart/HISE#426]
Hi everyone!

I'm new to HISE, and I am trying to get a grip on the language.

I want to make a copy of an array. And not just by reference, I want to make a proper deep copy. I see there is a function for this, the .map function for arrays.

Array.map(var testFunction, var optionalThisObject)

https://docs.hise.audio/scripting/scripting-api/array/index.html#map

But I don't understand how to use it. Can I get a script example that shows how to use it?

And here is a general thing that I have noticed. The docs seem to cover most things, maybe everything, but there are very little examples on how to use the functions. I don't think it is self explanatory. Especially not considering this is a custom language, even though it has similarities with javascript.

**Comment by davidhealey** [comment]
Array.clone()

**Comment by twiddlecoding** [comment]
Thank you. Where can I find information like this? It does not seem to be in the docs.

When trying to use it like this:
notespressed = notespressedvelall.clone();
I get "Can't assign to this expression"

I'm using HISE 3.0.1. Maybe Its a newer feature?

**Comment by davidhealey** [comment]
> Where can I find information like this? It does not seem to be in the docs.

It's not documented. It's one of a handful of hidden gems. But I did make a video about it:

https://youtu.be/inpAs00hWHw?si=hmY_vT5L00tVE4Yu

> notespressed = notespressedvelall.clone();

Is `notespressed` a const?

**Comment by twiddlecoding** [comment]
Yes, that was the problem. Thank you!
But why is that an issue? What's constant should only be the reference, right? Not the contents of the array.

**Comment by davidhealey** [comment]
You can't reassign a constant variable. The purpose of a constant is to be unchangeable. 

Simple example:

```
const a = [];
a = []; // Will fail
```

**Comment by christoph-hart** [comment]
I'll close that since it's not really an issue, but a question on how to script.
