### ISSUE TITLE
[Bug] Long line (big text chuck when wrapped) makes the text selection and display go haywire

### ISSUE THREAD

**Issue by aaronventure** [christophhart/HISE#427]
I was trying to edit the raw SVG data to split it into paths. Loaded it all into one line of text. 

Attempting selection results in crazy behavior. Deleting some of the data makes everything smooth again. Issue with the amount of data in a single line?

The gif doesn't do it justice as it's only 15fps. 

Win11. b33fa635e639a31bb0d5cc8252ada4e31ab13737

![selecting big text chunk](https://github.com/christophhart/HISE/assets/141569073/92464ffb-c512-4dcf-a58a-963a5a7df905)

**Comment by christoph-hart** [comment]
Yes that is one of the edge cases where the performance if the editor is really tanking.

I found it pretty easy to work around this issue:

1. put the long strings into a seperate file so you don't have to deal with them while coding
2. deactivate the word-wrap before you start editing / pasting stuff in the file as this is mostly responsible for the slow down
3. if this doesn't help and you need to edit it with word wrap enabled, paste it into Sublime or anything else, do the changes and paste it back. Yes this is essentially admitting defeat but we're making a framework for virtual instruments here and not a competitor to commercial text editors so I need to choose my battles wisely :)

**Comment by aaronventure** [comment]
No issue whatsoever working around this, I just figured I'd report it in case it's new behavior, as I haven't encountered it yet, but I've only been here since 3.5.0.
