### ISSUE TITLE
[Bug/Visual] Font bleed through when swapping projects

### ISSUE THREAD

**Issue by aaronventure** [christophhart/HISE#428]
1. Open project, load the xml preset etc. 
2. Have a font loaded as a certain string, e.g. "FONT_TITLE",
3. Open another project where you also use Engine.loadFontAs with the string "FONT_TITLE" by going File>Open Recent Project

Displayed font in the title is now that of the previous project, the one that was open on HISE load. 

Restarting HISE (which is now pointing to the 2nd project) and opening the xml preset displays the correct font. 

Win11 b33fa635e639a31bb0d5cc8252ada4e31ab13737

**Comment by davidhealey** [comment]
This has broken fonts (on Linux) when switching full expansions.
