### ISSUE TITLE
[BREAKING] Parameterized #define macros result in broken VSTi which refuses to scan/initialize

### ISSUE THREAD

**Issue by aaronventure** [christophhart/HISE#429]
If I have multiple UI components that share graphics, like a row of knobs, I will handle the placement using macros. This way any tweaking is done by simply adjusting a few parameters and the whole UI realigns itself. 

Here's one such macro:

`#define UI_PREF_KNOB_L_X(numberFromCenter) (UI.WIDTH/2) - UI.PREFERENCES_CENTER_OFFSET - UI.PREFERENCES_KNOB_DISTANCE * numberFromCenter - UI.PREFERENCES_KNOB_WIDTH * numberFromCenter`

It allows me to specify the knob number and it does the rest. 

This works as expected in HISE Standalone on Win11, b33fa635e639a31bb0d5cc8252ada4e31ab13737 .  I don't

But when compiled to VSTi, it compiles successfully and only on plugin scan/load does it fail. Reaper asks me to terminate the VSTi and blacklists it after 5 seconds. I tested with the consts replaced by magic numbers (int) and the result is the same.

I have the "Enable global preprocessor" in settings disabled, but I have #on at the beginning of my script.

I'm flagging it as breaking because it works in HISE, compiles successfully and then the VSTi won't load. 

It took me a bit to manually go through every change from a previous commit that worked and nail it down to the preprocessor. Is there a tool for debugging something like this, when the VSTi compiles, works in HISE but simply refuses to load?

**Comment by davidhealey** [comment]
What is the reason for the preprocessor for this and not using a regular UI factory function?

**Comment by aaronventure** [comment]
I've no idea what my reasoning was. I swapped the macros for inline functions and it's a single-line as well. Perhaps I didn't wanna clutter the watchtable? But then I can just write them inside of a namespace... I had to go back quite a lot, over a week. I guess I'll be compiling every evening now :D

**Comment by davidhealey** [comment]
This is the kind of thing I do for my UIs - https://codeberg.org/LibreWave/Rhapsody/src/branch/main/Scripts/Ui.js

**Comment by aaronventure** [comment]
I use helper functions as well, but then I feed the X and Y parameters with these (now) adjustment functions which can vary between sets of controls. Helper functions I set up once for the project, and that's it. They contain the functionality. But the actual positioning, which is highly relative, I set up this way. Then I have concrete parameters to tweak it, like KNOB_DISTANCE, ROW_DISTANCE, etc. 

It's actually faster for me to design a UI this way than using Photoshop/XD/Figma/Whatever. Plus, I can draw things with vectors here as well, and check how it animates in real-time, and do it all using math and trig instead of navigating clunky UIs with timelines and keyframes. I'm half-convinced that if HISE had an "Export Panel as PNG" which lets you define the resolution, number of frames and the range, it could easily add "UI graphical design" to its already silly list VI/Audio use-cases, so even if you want to deploy using something else, you could prototype and design everything here.

**Comment by christoph-hart** [comment]
The preprocessor is not used much in other projects so it's less tested and since it will preprocess the scripting code at the project export stage, it might cause an issue in the compiled plugin that wasn't there in HISE.

Can you make a minimal project that exhibits this behaviour then I'll debug it. I've only used the preprocessor for conditional exclusion of some code (which is the reason why I've added this), but if you want to move on with your project and not get sidetracked by this I would also suggest that you use inline functions for this (there should be no difference in the implementation for you here).

**Comment by davidhealey** [comment]
> Export Panel as PNG"

![image](https://github.com/christophhart/HISE/assets/14021202/184fcdc7-3643-45e1-bf37-908b11dc7bf5)

**Comment by aaronventure** [comment]
Open an empty project, enable VST3 support in the settings and put this into your onInit script, add a waveform synth then export VSTi. 

```
#on

Content.makeFrontInterface(600, 600);

#define UI_PREF_KNOB_L_X(numberFromCenter) (UI.WIDTH/2) - UI.PREFERENCES_CENTER_OFFSET - UI.PREFERENCES_KNOB_DISTANCE * numberFromCenter - UI.PREFERENCES_KNOB_WIDTH * numberFromCenter

inline function complexHelperFunctionForMyTwoKnobProject (name, x, y)
{
	local widget = Content.addPanel(name, x, y);
	
	return widget
}
const var testPanel = complexHelperFunctionForMyTwoKnobProject ("funky", UI_PREF_KNOB_L_X(1), 100);
```

notice how I didn't even declare the UI namespace or the consts. This compiles in HISE and the export goes fine. Of course the knob is not in the correct place because the constants nor the namespace were defined, but HISE Standalone puts it all to 0 and the editors gives the standard "Compiled OK" green light. 

If you remove the parameter of the define macro (numberFromCenter), then the editor throws the error as it should. 

Maybe this information helps you in chasing this down.

If you're failing to reproduce, here's a GD link to that same project folder with all the compile files, including the broken VST3 file. https://drive.google.com/file/d/1ZkHswii2cL4wdo6MhbKhrUX-ho1ZTo-J/view?usp=sharing

**Comment by christoph-hart** [comment]
Ah yes, that was in fact an issue where the preprocessor that is applied during the compilation stage didn't pick up the macro arguments so it threw a preprocessor error which wasn't picked up and messed with the project compilation. I fixed two things:

1. Make the preprocessor not fail in this case (so that the macros are correctly evaluated with the right parameters)
2. Abort the compilation if there is a preprocessor error.
