### ISSUE TITLE
[File Naming Convention] Rationalize naming schemes

### ISSUE THREAD

**Issue by qdr** [christophhart/HISE#43]
The naming convention of the Hise Project work-flow is kinda unintuitive. 

## Current Behavior
- Open Project then open .xml file (in folder XMLPresetBackups..)
- File/.hip in Presets Folder
- User Presets.preset

## Expected Behaviour
- Intuitive naming schemes.  
- Project > File/.hip | Presets

**Comment by christophhart** [comment]
krasser fall von #nofix
