### ISSUE TITLE
Using const instead of var in a namespaced inlined paint routine function that's used for 10+ controls crashes HISE

### ISSUE THREAD

**Issue by aaronventure** [christophhart/HISE#430]
My paint routines are in a separate file within a namespace PaintRoutine. Each one is in its own inline function so it can be called when necessary. I was going down the list of variables, swapping var for const, and when I did it for my leadPath variable (which gets assigned to later in the code - obvious mistake, as it should stay var in this case), HISE crashed. 

I tried to reproduce this in an empty project, and setting up the control and the skeleton paint routine with the leadPath being const only threw the "const needs to be on global scale" error. I put the whole thing into a namespace and an inline function, then the error became "parameter undefined" and pointed to the line where I attempt to add an arc to the leadpath.  

Then I added 12 more controls and set the paint routine for all of them, and then HISE crashed (just like in my actual project. Here's the code that causes the crash. Paste this into your empty onInit callback

```
Content.makeFrontInterface(600, 600);

const var crash = Content.addPanel("crashMe", 0, 0);
const var crash2 = Content.addPanel("crashMe2", 0, 0);
const var crash3 = Content.addPanel("crashMe3", 0, 0);
const var crash4 = Content.addPanel("crashMe4", 0, 0);
const var crash5 = Content.addPanel("crashMe5", 0, 0);
const var crash6 = Content.addPanel("crashMe6", 0, 0);
const var crash7 = Content.addPanel("crashMe7", 0, 0);
const var crash8 = Content.addPanel("crashMe8", 0, 0);
const var crash9 = Content.addPanel("crashMe9", 0, 0);
const var crash10 = Content.addPanel("crashMe10", 0, 0);
const var crash11 = Content.addPanel("crashMe11", 0, 0);
const var crash12 = Content.addPanel("crashMe12", 0, 0);
const var crash13 = Content.addPanel("crashMe13", 0, 0);

namespace PaintRoutine
{
	inline function test(component)
	{
		component.setPaintRoutine(function(g)
		{
			const leadPath = Content.createPath();
			var pathArea;
			
			var startOffset = Math.toRadians(135);
			var endOffset = -startOffset + 2.0 * startOffset * 0.5;
			
			var arcWidth = 0.55;
		        var arcThickness = arcWidth * 0.08;	
		        var arcX = (1.0 - (arcWidth + arcThickness)) / 2; // centers it horizontally
			
			leadPath.addArc([arcX, arcX, arcWidth + arcThickness, arcWidth + arcThickness], -startOffset, endOffset);
			pathArea = leadPath.getBounds(a[2]);
		    g.drawPath(leadPath, pathArea, a[2] * arcThickness);
		});
	}
}

PaintRoutine.test(crash);
PaintRoutine.test(crash2);
PaintRoutine.test(crash3);
PaintRoutine.test(crash4);
PaintRoutine.test(crash5);
PaintRoutine.test(crash6);
PaintRoutine.test(crash7);
PaintRoutine.test(crash8);
PaintRoutine.test(crash9);
PaintRoutine.test(crash10);
PaintRoutine.test(crash11);
PaintRoutine.test(crash12);
PaintRoutine.test(crash13);
```

**Comment by davidhealey** [comment]
Use `local` in inline functions, not const

**Comment by aaronventure** [comment]
That goes for sure, I just wanted to see what happens when I use const and accidentally used it for a type that I assign to later, which normally just throws an error, but when it happens multiple times in a row, I guess it crashes.

**Comment by christoph-hart** [comment]
> I just wanted to see what happens when I use const

It should throw an error. Currently it doesn't, however if the inline function is not defined within a namespace, it will throw an error so the parser is not catching this case. I've fixed it so that it will throw an error whenever you want to declare a const variable inside a function or inline function body.
