### ISSUE TITLE
Visual Studio Code not selectable when compiling

### ISSUE THREAD

**Issue by Arthur-McArthur** [christophhart/HISE#436]
Hi, I'm on the latest dev version, with Visual Studio Code latest version on Win 11. When attempting to compile, the Choose Application dialog does not show any options.

**Comment by davidhealey** [comment]
https://youtu.be/D3kthNOQ9_s

**Comment by Arthur-McArthur** [comment]
Excellent tutorial David, thank you. That has got me sorted and I'm off to the races!
