### ISSUE TITLE
Autocomplete broken?

### ISSUE THREAD

**Issue by aaronventure** [christophhart/HISE#454]
![hise autocomplete](https://github.com/christophhart/HISE/assets/141569073/b215ee1a-3152-40b9-9221-abec1ebc2e6d)

b80968f944465e5fe633e61a125d728a4eaeac64

**Comment by christoph-hart** [comment]
Is it fixed if you hit F5 to compile the script? 

I've rewritten some of the token building logic to fix some crashes but I noticed that you need to compile the script now once after opening the editor.

**Comment by aaronventure** [comment]
Used to be like that when I was on the early November commit (last develop commit before the one from the other day), but now it just straight up ain't showing up.

I'm looking at the API reference so much I'll actually end up learning all the methods by heart.

**Comment by christoph-hart** [comment]
Can you check again now? The autocomplete wasn't working after you switched tabs in the editor until you recompile (or click on the show workspace button in the module browser), but this is fixed now.

**Comment by aaronventure** [comment]
![hise auto changing](https://github.com/christophhart/HISE/assets/141569073/d3c1e072-85c3-4363-bf97-8b97333850fa)

**Comment by aaronventure** [comment]
Elaborated on here https://github.com/christophhart/HISE/issues/497
