### ISSUE TITLE
[Bug] Limiter FX Value Entry Only Takes Normalized 0-1

### ISSUE THREAD

**Issue by aaronventure** [christophhart/HISE#459]
1. Add a Limiter to your master FX
2. Click on any value and type in a different desired value

You'll realize it only takes 0-1 for all controls, instead of the actual value.

**Comment by christoph-hart** [comment]
I solved that problem by removing the entire module :)

**Comment by aaronventure** [comment]
That was done a bit ago, right? Is it because it already exists in the Dynamics module?
