### ISSUE TITLE
 [bug] Table envelopes always jump after attack completes 

### ISSUE THREAD

**Issue by davidhealey** [christophhart/HISE#471]
If the last node of the attack envelope is not 1 or 0 then when the end of the table is reached the envelope will jump to 1, even if the note is still held down.

![ZPnGU7s](https://github.com/christophhart/HISE/assets/14021202/7780d697-08d5-4882-b9c7-a3023a308ba0)

Forum thread - https://forum.hise.audio/topic/7183/bug-table-envelopes-always-jump-after-attack-completes

Removing this line solves the issue, but I don't know if that will cause other problems... https://github.com/christophhart/HISE/blob/develop/hi_core/hi_modules/modulators/mods/TableEnvelope.cpp#L324

**Comment by aaronventure** [comment]
Man, you've been after this for a year now, even found and tested the solution yourself, almost feels like Chris is just fucking with you 😂
