### ISSUE TITLE
[Bug/Breaking] OSC Data Loss

### ISSUE THREAD

**Issue by aaronventure** [christophhart/HISE#490]
Testing this within the same instance. So I figured I found a workaround for my "sending instance self-executes" problem when toying with crosstalk. 

Consider the code

```
namespace OSC
{
	// The domain takes the project name
	const var domain = "/" + Engine.getProjectInfo().ProjectName.replace(" ", "");
	
	// Error logging
	inline function printError(message)
	{
		Console.print(message);
	};
	
	//========================================================================================
	
	// Set up the receiving routing manager
	const var routingManager = Engine.getGlobalRoutingManager();
	
	// This callback triggers on message received
	routingManager.addOSCCallback("/reloadSamples", function(id, value) 
	{
		 if (value != Config.instanceID) Engine.reloadAllSamples();
		 Console.print("Received: " + value);
		 Console.print("Should have received: " + Config.instanceID);
	});
	
	// Set up OSC for this manager
	routingManager.connectToOSC(
	{
		"Domain": domain,
		"SourcePort": 8000,
		"TargetPort": 8000,
	}, printError);
	
	routingManager.sendOSCMessage("/reloadSamples", Config.instanceID);
	Console.print("Sending: " + Config.instanceID);
	//========================================================================================
}
```

All instances of the plugin will have their own unique instanceID generated by a combination of system time and a small float added for randomization. Basically impossible to have two instances with the same ID.

In this case I am testing in the callback whether the value received is the same as value sent. 

It's not. 

```
Interface: Sending: 0.3271708066775753
Interface: Received: 0.3271708190441132
Interface: Should have received: 0.3271708066775753
```

Data loss occurs after 7 decimal points.

**Comment by aaronventure** [comment]
It's not just after 7 decimal points, it's always. Any float/double loses data. 

![image](https://github.com/christophhart/HISE/assets/141569073/e46d4f95-7f82-448e-b0f2-83445ebc0daa)

![image](https://github.com/christophhart/HISE/assets/141569073/ec858d9f-909a-4031-91cb-de831214377f)

**Comment by christoph-hart** [comment]
yeah, that's basic floating point behaviour. You get 7 digits of precision for single precision and 14 for double precision.

Just don't rely on it being completely equal. In your case a big random integer should give you bitwise equality while keeping the chance of collision below you winning in the lottery without even playing.
