### ISSUE TITLE
Compiling of a Polyphonic FX With a Selector Node Fails

### ISSUE THREAD

**Issue by aaronventure** [christophhart/HISE#521]
![image](https://github.com/christophhart/HISE/assets/141569073/87355d5d-ca9b-49e6-8a1d-0921c7c75db3)

![image](https://github.com/christophhart/HISE/assets/141569073/b5c5e76f-dcc0-4435-a50b-03f9fda31098)

macOS 14.4.1
ebfbd32d1fa3f4d38466ff4609509e7e25b16b0d

**Comment by christoph-hart** [comment]
Ah yes, I didn't expected that this node might be used in a polyphonic context, but now it should compile.

I also made the ChannelIndex the only "polyphonic" value (so you can route different voices to different outputs now). The other parameters are still monophonic (as in you can't change them between voices), but that should be fine as I can't see any reason to do so.

**Comment by aaronventure** [comment]
Nice! Yes, this was my attempt to create per-voice routing: I wanted to compile the network and add a script voice modulator. 

But with the new event nodes, there's no longer the need to compile it.

**Comment by christoph-hart** [comment]
Yeah, this in combination with the event data makes it a very nice solution for dynamic voice routing. I've added a snippet to the browser that demonstrates this use case (Dynamic voice routing).
