### ISSUE TITLE
[Fatality] SVF Allpass attempts to blow up my system with a 400+ dB spike

### ISSUE THREAD

**Issue by aaronventure** [christophhart/HISE#527]
Nice try. 

Old habits die hard so I work with a limiter at the end, always. But here it is. I caught it as it was coming down. The initial peak was over 400.

![image](https://github.com/christophhart/HISE/assets/141569073/3fe8b503-0c29-4165-bc41-d737d71b3610)

To prove that it actually went outside of HISE, here's my Babyface Totalmix, it's been just sitting like this. After resetting, I saw it read +35dB for a moment as it was resetting. That's fucking scary. 

![image](https://github.com/christophhart/HISE/assets/141569073/af45b5ac-2e0f-4f86-bd53-13af06a5570f)

```
HiseSnippet 1503.3oc2X0saSbDEd13rAb.p.Jn1d2JQuHHghx5PoUpWXmDGCQEm3lMMPuJcX2wwi7tyrc2YShopWQufa6CQunpuD7.PkPhWf12fzmf1yrytd20dwXbAJTGoHOmyYly24+Ybm.tMILjGfzpt2.eBR675VCXhdazCSYnsZhz9.813PAIvPQZ8A93vPhCRSqxskDzpNOJ9yo0WG6hY1jLRHz9bpM4tTOpHiZmFeE00sE1grG0Kmz2rwV1b1FbWdDfmJ5qf7w18wGR1FKEaNcj1Ba5PE7.KAVPBQZyuN2YfUO9wLk76SCoOvkHWXhrfCRQtE20QhXIUzF8ntNcRs6PDRSuSlWnhxKbE81TG5P5YdiKFyvHaG48GZyUDdUJ.Oy7vakbvqDHokCRyqfzkzsrCn9hLNR7bN8sXPvoKFb64ghRVj1Sz2fCBvDK6g6SZE.KFtgkt0JqbCC3eW+K6FwrETNyfy1lKH6vV55K9CKVcwebQiQY0sao7jpIf65RBJksLRGLoMtDKx6AjfaXbD1MhLTPv7K5S0ew9z7gbakUmSPNaKFUriOg8hRDPItJ3aeyVMwBrLPjPCjymDHnRHn0jbDjUqBKU0aRB6K39Pd8XwLHag6D4hEESgj0MIL.ePg3lL3vBohA4qqdskWMsP7R5cnB6dkiw4JAifm5MAFSpFuf9lc6RrEY.bd8V2+MTo2bi6iVLozCzoT4mOYoQq6aVZQ2i0yRv8CH93.xd7Nt3AKEh87cI6BX7FFOvka22h9Px3UE9JHrtThkr6gYLha3rT7rvT6ULmbPYWdjfxNrMVDPOApB2NxyBZSaS1HAc.Ms4j0Pp0qHWKyKrHLm3E+M7IgoobsVBSyTl4J+1lHNlGzOtSXx2QZmQ46CicxGz8DSzZtt7i2f64SSxRgXPLsNb2A983LpsjjRhTjtlGOBTRBbuCNbOL0UlVaEEBMGb1gYABGOFSqx9jfv3C9L5qrL7GjdrM2AXo2BaCN1Acvhdx5EY+FH4jDrr8vjzBXMedh7HRGyo7R.D8jld7PtJ4Z1nFEHWAUayoN0sB2Wx0F6h1WFukfGIOSk+RgOon55gG0EU.oWPuK0E5+Gtrj0rBJIKHO9jzljsTmY1WkXk4PNIM1tIjd5.yfi2PZ7tCN.FrmrwEFtB9daJKwxxtaPa7IEo83m2vRP7kUP4aDY0mbrxjSn13Qd+dc0rxVAjuOBhsCPCOpG8aexOevu9KMPSP+MVc0mWeD8+jm9zqMc5Gcs+5Yw5uh9WiFwrNsNZx1csmLlcipMk5Ud7R8tP7.mQUsrS6DUMBMtpOs9To5u6Ca97DWtkGmK5AsNJn+F+4C+o5yf9uXIlNfoIX5skkCicJulL8Io5p5axvPyUmIEyk0Rqy488vwc69WeuiKmNvp4.F1iZGlbIwzklib+cAIEj4rcI485EPB6A2adTFqIDvkxyaMRp6RbI3vbF421P1hHHFVknhLlkpnL16JarmWaYrFEIeZNUVBdheDBYbvbZ8DNkhjDdia0ILFSQ4QQa3J2Q9kbbiyPqx6SSpykwcUUF24zuG9HR7SGiS4tZ75t7.OiaSfwhx6WZNgGO9ro8wi9S8iG2wV.PXu.LKzmGRLyexivqVddMIhHVQwUjJHkz7ZAlWN4NaiTh0xSrClU3vf0ENo1xvT5x+ntJA0h.ViyNg1fwhGo6RmH2Px8nNhdl42XF4Z4IeGbfCDWrmT117SW11K4czK7N26neO3IYEdpe0TLZQk2uZS1QDWn+eLFuLzvuKNxUjRsX4TaNimdk2r.8tDnKvgGRJNcpLCZzNbWoQIs1tKbCWbP7H0YyWX9J+ydTZ75i0Uv0P1Cv382mRW4+0Okd5q9fVfuaGE+HcnUbMi3Pow+Mwx2Fy0eanCOrc.+.a0Obgrn+rwT.6lE+y7VUusbsgI5nQuTtGLx3.a6hG0Xar1rtwUm0MdyYcie1rtwaMqa7ym0M9Eu7MJmnuVjf6opMfa1zYS0C90FdqasJn+g9fJWK
```

macOS 14.4.1
9d0b36cc0e5c4dc9d5c5bc3f434323322fa13fe1

1. Load snippet. The limiter at the end prevents it from going above 0 dBFS. If you remove it, turn off your speakers or something. 
2. Open the scriptFX. 
3. Play a note. The waveform generator should sing a saw.
4. Move the svf filter frequency up. Somewhere between 7kHz and 10kHz, it'll blow up.
5. After this, I think the audio engine stops. I can't get a sound of HISE, and if I close it, a spike happens again.

Second attempt at my life within a month. The first was this :D https://forum.hise.audio/post/79909

**Comment by christoph-hart** [comment]
who would have known that dividing instead of multiplying will blow up a signal :)
