### ISSUE TITLE
Software compilation failed

### ISSUE THREAD

**Issue by NkeoPatch** [christophhart/HISE#534]
![image](https://github.com/christophhart/HISE/assets/93478678/9efbcc75-d008-4362-89fe-32f72178c01f)
The header file iasiodrv.h is missing

**Comment by davidhealey** [comment]
Did you extract the ASIO SDK?

**Comment by NkeoPatch** [comment]
> Did you extract the ASIO SDK?

Sorry bro, I missed this step
