### ISSUE TITLE
[Engine] ScriptNode Split node dies on reload

### ISSUE THREAD

**Issue by aaronventure** [christophhart/HISE#538]
I'm encountering a serious bug with the Split node. 

```
HiseSnippet 1182.3oc0X8zaaaCEmxNzIwo6OEnXm8wTff.6tttBrCIwNwaFqNQnJKn6T.CEcLgoHEnnRr2vtua6busuF619H0uAaOJJGKY6llXrk0o.DH99C4O968djOYeshxRRTZj2lmNIlg7dDNXhzLryPBWh5cHx6Sw8IIFltgST6IwjjDVHxyq52ZE3s4Znrm2sWahfHorYhPnyTbJ6U7HtYlT+8+dtPzkDxNkGUv5mueOpR1QITo.dphahhIzQjKYGSrlUAi7pcTH2nzAFhgk.1zVENIXn5Zoy9y3I7KDL6fVn.XhbhQcFxEg9S2qIHj2Z9y14Uc67mf6yC42HeFC74YJZLyihbfWkaCRstGPxq.jVyAoGiCnZdrYlFKd1B2SBAjADfpKBEmsHu+D2QAFHM6FQFw5pgA23v1unYycZ.+6oeyfTI0vUxFJ4wJC6D41Os9OWey5+R8FyqZvfkpytLZkPvzKUsM5puMG2VlFcASuSiqHhT1MFBa+xbZs6FmRc65BFpj8jbyIwr7wcUhPKWYeewH.Jm1f29gdGRLDaPIWFXWLSa3V33cH6JHq1Eh1DeHKYjQEC40KD+fLGUXpfXJmNYqaxU.7QoXnMPIS3lIEqqtG4XMu0br6JDeL1manCWNFqrDLBL0+FXLux7SvGMX.iZlAv0vceypVF17dWFVOuLDVS6h+n7gM59lVKs.7WwyR1i0rXhlcpxWPlrcBIJVvdMfwcZbgPQGEv+I1hUHwNHz1Zw1zgDojIRVkBoZ+Cc3D50pTCWdYehQyGi7vGmFE.GSSYcxQGHyqhsFxMtocrMuHfICyF7WvStxV1wd4JaMUYgxuiYlqU5QYgi72Qdq639jLR97AiagNPHTW2QEEyyyRgXPlLekXR7PkjSshbVLEoGDoRgEIGteGI4TBWXSqCRSfCJBOQF.FmcMlW0yX5jrIdcbycg+fz7iUgfJbWBEH1I9DyPa8h8rGH4jo2kdSRZIrVLOwNESulywR.Dira8rK4pV3vFW9ncDTsUwMq8RNypkRDnyrwaK3Q14zwWY3qlyzA7wmmkmMFUBveQA.Wvl6NHsIQ9DMbwLbwh8LwJyA6J2MXOmUagaOspXpQUwuDM+tCasccrip+.QhGXhOGZIwBnkm2KzbpWUnsz0rNNREtDF4IEV1ar3+BRYCW7p0GiArMbArVOnQrbB4YerPHUJfsZXn1NtLx1BPllsalh6AlVqDQLqmhSI5KYFWeW1aEGOskqC4.YSlzNEtz2ckbII1MiLjMd58FGAW8EBs0k49z6RJb1jkUlNB1X84x7sdVyK+9ae6erWex3hxPn8+s8CLr3rygJXWvH10NJoX6YNp0mo4pvruno7bg9w8Q2B.xdV..vzNG.xdd+.XK7qTpX3hdsAsvz+.r90ftZMKr0e2dnBIUeFNlQFcdpLAR.gbmENmBxtJaw+mRydvFzVoFEQxZOZ09PkGhl4hHTs5bpq+TK6tQlDnXTl807ah6aG2nE5p4SFifu19bJs7TsfiOaUc7KWUGe9p53WspN9hU0wudUc7keXGs+XHGjZTQtdtgZM+ibEEdGIIWHbUqn+lMoEgm
```
Open the snippet. You'll see that there's no signal in the deepest chain node. 

If I move the chain2, where the ramp and peak_unscaled are, outside of its parent split node, it starts working again. 

if I move the entire chain outside of the fix_blockx, it starts working again.

![splitdie1](https://github.com/christophhart/HISE/assets/141569073/43b0e7be-c170-40d1-a1cb-e4bb524260fa)

You can recreate this in both a saved and an embedded network, but the kicker is that you'll only be faced with an issue ON LOAD i.e. when you close HISE, open it and boot the project up. So if you left yesterday and all was working, you're now coming to a network that doesn't work. 

I have no idea why, but this is the pie recipe:
fix_blockx > chain > split > modchain >chain >split > chain > [ramp, peak, peak_unscaled etc].

Now save the project if it's a file or export the snippet if it's an embedded network. 

Close HISE. Open HISE, load the project/snippet.

If you just load my snippet, it should already be dead.

macOS 14.5
62247f62186b5461b34f1f6137e51bf3ef3e4c23

**Comment by christoph-hart** [comment]
yup, good catch, the issue was that you're getting a "block size" of a single sample (through the fix_block set to 8 samples and the modchain using the 8x downsampling for the control rate). This then triggered a logic where it skips the processing because it thinks it has to do frame processing.
