### ISSUE TITLE
[UX/ Scriptnode] Copy/Pasting Nodes Is Broken

### ISSUE THREAD

**Issue by aaronventure** [christophhart/HISE#546]
When you copy a node, or import a snippet from the clipboard, HISE will:
* paste the nodes with the exact same ID
* apply the connections from the clipboard based on ID, 
This breaks the core ScriptNode functionality where each parameter can only be modulated by one cable at a time.
![copy paste scriptnode](https://github.com/christophhart/HISE/assets/141569073/25db88b3-a046-4c3d-b180-5e439a851805)

What should happen is: 
* HISE should check what the new IDs will be for the pasted nodes
* change internal (within the copied nodes) connections so that they refer to the new IDs
* keep any incoming connections from the outside, e.g. from the main parameters or other nodes
* break any outgoing connections that go beyond the copy scope

The lack of proper implementation of this has some severe effects on the workflow for complicated networks:
* it's impossible to duplicate more complex modchains, effectively having you go through the entire setup any time you need a copy
* if you already developed a modchain within the network, but it grew to be too big, it's not possible to "move it to a separate file" like you can do with code in the code editor, so that you can then reimport it as a project node, because the connections will not copy over properly

**Comment by christoph-hart** [comment]
Funny, the duplicate function already works properly (Ctrl+D) which I was using all the time so I didn't spot the issue in the 2-step copy & paste version.

Should be good now.
