### ISSUE TITLE
Building HISE on WinARM seems to take longer because of the 32-bit linker 

### ISSUE THREAD

**Issue by aaronventure** [christophhart/HISE#550]
Running inside a VM Windows for ARM on macOS 14.5, M3 Max.

So it starts linking with the 32-bit linker, fails, then restarts with 64-bit. Why not just do 64-bit from the get-go?

![image](https://github.com/christophhart/HISE/assets/141569073/ea30a3f7-e5cd-4208-b5c5-b61c6d2265c4)

**Comment by davidhealey** [comment]
I think that's a VS problem rather than a HISE one
