### ISSUE TITLE
[bug] setKeyPressCallback is broken on all operating systems

### ISSUE THREAD

**Issue by davidhealey** [christophhart/HISE#570]
On Linux and Windows you can't type anything into a label when the setKeyPressCallback is set.

On MacOS you can type into the label but pressing return, esc and backspace doesn't do anything.

There is a long forum thread about this but if you start at this post you'll find examples of the issues on each OS

https://forum.hise.audio/topic/9566/return-the-old-content-setkeypresscallback-functionality-that-we-had-for-a-few-days/20?_=1724059564612

**Comment by christoph-hart** [comment]
I think I've fixed all OS with the option of adding a non-exclusive catch-all behaviour by passing in `"all_nonexclusive"` into `setConsumedKeyPresses()`

I've also extended the docs here to show the new magic spell:

https://docs.hise.dev/scripting/scripting-api/scriptpanel/index.html#setconsumedkeypresses
