### ISSUE TITLE
[Visual/Info] LAF Function Continuously Spamming the Console Log, but No Other Methods Get Executed

### ISSUE THREAD

**Issue by aaronventure** [christophhart/HISE#571]
Calling Console.print() in a rotary slider LAF keeps spamming the console log, while the paint routine behaves as expected.

See thread:

https://forum.hise.audio/topic/10350/laf-function-continuously-spamming-the-console-log-but-no-other-methods-get-executed

macOS 14.5 

cd51dc7bc8d5f539184a4308b41c6b5cabc2aaaa

confirmed as far back as 195af464154a7eb21a1a006b35990b74dcb97217 (I didn't feel like reinstalling FAUST to test this)

**Comment by davidhealey** [comment]
Confirmed here on MacOS 13.4.1

Doesn't affect Windows or Linux

**Comment by christoph-hart** [comment]
Not sure if this qualifies as bug, the look and feel method will be called directly on the UI thread to create the paint actions that it needs to render the slider / knob (while the panel's `repaint()` method triggers an event that marks the previous commands as dirty and then executes it once).

So what you're seeing is not a hidden UI timer, but the OS thinking that it needs to repaint the slider (for some reason).

But yeah, having the LAF methods execute directly in the message thread is one of the more annoying design decisions with HISE (I spent multiple days tracking down complex multithreading issues that eventually came down to this). One reason more to love the new CSS renderer...

I think I'll close that now as there's not much to fix here...
