### ISSUE TITLE
Analyser LAF functions' (drawAnalyserPath etc.) obj is missing the id property (obj.id) and the parentName is always empty

### ISSUE THREAD

**Issue by aaronventure** [christophhart/HISE#580]
This forces the hardcoding of target component ids into the LAF functions which is kinda dirty.

**Comment by christoph-hart** [comment]
fixed with 

- added id property to all LAF object arguments Christoph Hart <christoph-hart@gmx.de> b0d414e58666f4f4e959316503cd22651a0d83f8 13.10.2024 18:18:13
