### ISSUE TITLE
[REPL Convenience] Differentiate between REPL Input and message behaviour

### ISSUE THREAD

**Issue by qdr** [christophhart/HISE#59]
## Current Behaviour
* I want to type something in the REPL and have to delete ("Compiled OK") or an error message 

## Expected Behaviour
* when focussing REPL-console cursor moves to start (">") 
* REPL message should be un-editable. ("why should anybody want to do that?") 

## Proposal
* greyed out REPL feedback messages 
* fix perhaps combinable with [Feature] placeholder behaviour -> #48

**Comment by christophhart** [comment]
If you right click, it shows the expected behaviour. This appears to be inconvenient, but the problem is that the double click is used to jump to the location. If it deletes the text on the first click, then it won't have anything to jump to after the second click.
