### ISSUE TITLE
Compiling HISE on Fedora 41 makes Welcome screen empty and panels not render in plugin UI

### ISSUE THREAD

**Issue by minosimo** [christophhart/HISE#592]
Compiling on Fedora 40 is fine. With HISE compiled on Fedora 41, several panels are empty, namely the "welcome" and "New Project" windows. The plugin UI in the editor and in VSTi exports is also affected, it looks like all Panels do not render. Do you have any hints as to what libraries might be causing this? Worst comes to worst I suppose I could downgrade all the dependencies one by one until we find the culprit!

When opening HISE:
![image](https://github.com/user-attachments/assets/b40267c5-682e-4042-80ba-9e72b73929fb)

New Project: 
![Screenshot From 2024-10-27 20-34-04](https://github.com/user-attachments/assets/bddc5bab-8925-4f3d-8393-833949aeff56)

**Comment by davidhealey** [comment]
My guess is you're using gcc 14?

If so it's buggy and I've reported it on the forum. Use gcc/g++ 11 until it's fixed.

https://forum.hise.audio/topic/10597/bug-multipage-dialogs-with-gcc-g-14

**Comment by minosimo** [comment]
I'm not sure why it would have worked on Fedora 40, which is also gcc 14. Maybe a subversion makes the difference?

**Comment by minosimo** [comment]
Some commit in the last few months is responsible. I switched to compiling in a Debian Bullseye VM for now.

**Comment by davidhealey** [comment]
> Some commit in the last few months is responsible

Are you saying you are able to compile with gcc14 on an older HISE commit and the welcome screen/broadcaster wizard, and other multipage windows display properly?
