### ISSUE TITLE
Libux build issue with libfreetype

### ISSUE THREAD

**Issue by brotenet** [christophhart/HISE#597]
Hi,

I am trying to make a Linux build but I keep getting fatal errors on the FreeType library header ft2build.h not being found.
![image](https://github.com/user-attachments/assets/d79f88fb-eb0b-4cd0-b8f0-5bf3f38fcf7d)

I have already installed the libfreetype6 and libfreetype-dev packages from the Ubuntu repository but I still get the same error.

I working on Linux Mint 22 which is based on Ubuntu 24.04 noble.

Also, I am (by all means) not a C++ developer, so ...be kind in your responses please :anguished: :grimacing:

Any help will be greatly appreciated.

Thank you :smiley:

**Comment by davidhealey** [comment]
Hi,

Please see this post - https://forum.hise.audio/topic/9968/default-value-of-a-slider-doesn-t-change-and-the-slider-value-always-jumps-to-zero/43?_=1730631461038

**Comment by brotenet** [comment]
Thanks David.
I will give it a try and update this ticket with any results before closing it.

**Comment by brotenet** [comment]
Nope.. :neutral_face:  I keep getting a FreeType related error but this time it's for fftw3:
`AudioFFT.cpp:52:12: fatal error: fftw3.h: No such file or directory`

![image](https://github.com/user-attachments/assets/e585be48-729c-425b-8bed-d79d78aead8b)

**Comment by brotenet** [comment]
I tried a new build after installing the FFTW3 library (sudo apt install libfftw3-dev) and it continued building up to the point that it gave the following GTK dependency error:
`juce_gui_extra.cpp:116:11: fatal error: gtk/gtk.h: No such file or directory`

The problem now is that I do have the required dependencies for GTK already installed (please have a look at the below screenshots):

![image](https://github.com/user-attachments/assets/8f838781-c4ba-4b11-be66-ffe1d6ec9e5d)
GTK headers are pointing at the correct directory.

![image](https://github.com/user-attachments/assets/31661980-9438-4390-8fdc-0c42d8fd3f36)
The "gtk.h" header file already exists in the correct directory.

![image](https://github.com/user-attachments/assets/95da42fb-181e-4d9f-bb85-333408acd9f6)
But the build fails to pick it up ...? ...i guess?? :confused:
