### ISSUE TITLE
[Visual] ScriptNode connection mouse icon is misleading

### ISSUE THREAD

**Issue by aaronventure** [christophhart/HISE#603]
When dragging a cable in ScriptNode, the actual target point is the top left corner, not the middle as cursor graphic suggests. If the current graphic's alignment cannot be changed (due to OS cursor settings or whatever), an a different cursor graphic should be used (which correctly communicates that the connection point is the top left corner of the cursor).

macOS 14.5
2636d04cfbf2ff883e06a3b1391493d50e630df4

**Comment by christoph-hart** [comment]
Yeah I think maybe using the default "crosshair" cursor should put the hit point in the middle.
