### ISSUE TITLE
Git commit info in About HISE is donezo?

### ISSUE THREAD

**Issue by aaronventure** [christophhart/HISE#645]
Is that going away? The latest commit still points to the commit from Nov 7. Is this whole thing manual?

Can we at least get build time/date in the About window?

**Comment by christoph-hart** [comment]
It's semi-manual. I just have to run a batch file before every commit that fetches the last commit SHA and writes it into the source code, but when my commit frequency goes down like in the last month so does the muscle memory of doing that.

This will magically resolve itself when I'm back to working on HISE in January.
