### ISSUE TITLE
Assert crash 

### ISSUE THREAD

**Issue by borg** [christophhart/HISE#76]
I'm running through Xcode and this happens both when compiling player and when used as audio unit within another framework.

It seems when too many voices are played and released at once the assertion fails. Basically either running mouse over virtual keyboard or banging midi keys.

JUCE v4.3.0
JUCE Assertion failure in StreamingSampler.h:606

``` 
void setSoundToUnmap(const StreamingSamplerSound *s){
	jassert(sound == nullptr);
	sound = const_cast<StreamingSamplerSound *>(s);
}
```

commit 59ffb80eccea7cdf851299aefe092edd92ae89bc
Author: Christoph Hart <christoph-hart@gmx.de>
Date:   Wed Aug 16 16:04:46 2017 +0200

**Comment by christophhart** [comment]
If you're running HISE in Debug mode, then it might be very well possible that it will behave weirdly in a performance-dense scenario, but I'll take a look.

**Comment by borg** [comment]
You are right. I haven't seen it in release mode. Thx.
