### ISSUE TITLE
 - script autocompletion issues

### ISSUE THREAD

**Issue by qdr** [christophhart/HISE#8]
Script-Autocomplete crashes on several occasions. Havent figured out, exactly why..
   - with content marked?
   - with accidentally CAPSLOCK? 

![bug 6](https://cloud.githubusercontent.com/assets/8782378/19515703/d1529ebc-95f8-11e6-8882-424e9cf9fa98.gif)

**Comment by christophhart** [comment]
Can't reproduce it, but I fixed the null pointer access.
